#ifndef SERVAL_AUDIO_H
#define SERVAL_AUDIO_H

// Sound. See docs/audio.md.
//
// Two kinds of sound, each with its own music player:
//
// - The PSG (implemented): the GBA's tone generators, two square waves and a
//   noise channel, which cost almost no CPU to play. Sound effects (PsgSound,
//   psg_play()) suit bleeps, hits, jumps, pickups and short jingles; songs
//   (PsgSong, psg_music_*()) play looping chiptunes of notes on the same
//   channels, and sound effects take a channel over while they play. The
//   fourth tone generator, the wave channel (PSG_WAVE, psg_waves_set()), is
//   planned.
// - Tracker music and sampled sound effects (planned): modules (MOD, S3M, XM,
//   IT; music_*()) and recorded samples (WAV files; sfx_*()) from one sound
//   bank (audio_bank_set()), mixed in software into the Direct Sound channels
//   by Maxmod (the BlocksDS fork) while the PSG plays on. Unlike the PSG,
//   mixing costs CPU time for every channel playing; the engine's figures will
//   be measured when it is implemented (docs/audio.md has Maxmod's own).
//
// The two music players are separate and can play at once: psg_music_*()
// play a PsgSong on the tone generators (scripts reach this one, through the
// VM's psg_music_* SYS calls), music_*() play a module from the bank. Their
// volume ranges differ: psg_music_set_volume() takes 0-15, the tone
// generators' own steps; music_set_volume(), sfx_set_volume() and
// sfx_play_ex() take 0-255, the mixer's finer steps, so fades are smooth.
//
// frame_end() steps sound once per frame, after the VBlank flush: PSG sound
// effects, then PSG music, then (once implemented) the mixer, which mixes the
// next frame's samples; Maxmod's VBlank handler will run in the engine's
// VBlank interrupt.
//
// Planned names compile with a warning, and in this engine version do nothing
// and return false or SFX_NONE, warning once in debug builds
// (docs/releases.md#planned-api). On the web the PSG plays as on the GBA;
// tracker music and sampled effects will stay silent there (the calls work,
// play nothing and warn once) even once the GBA plays them, until the web has
// a player of its own. Future targets: GB/GBC has the same four tone
// generators but no Direct Sound, so only the PSG will play there; DS will run
// Maxmod's DS version behind the same calls.
//
// Like sprites, PSG sound effects are constant tables (normally generated by
// Studio Advance) registered with psg_table_set() and played by ID; songs are
// constant data played by pointer.

#include "serval/platform.h"

// PsgSound.channel and PsgTrack.channel: the tone generator that plays. Each
// channel plays one sound at a time; playing a new sound on a busy channel
// replaces the old one unless the old one has a higher .priority. Other
// values are refused: psg_play() skips the sound, psg_music_play() leaves the
// track out (both warn).
#define PSG_SQUARE1 0 // square wave that can also slide in pitch (PsgSound.slide)
#define PSG_SQUARE2 1 // square wave
#define PSG_NOISE 2   // noise: hits, explosions, drums
enum {
    // The wave channel (planned; docs/audio.md#wave-channel): plays a
    // waveform of 32 4-bit steps (psg_waves_set()), so it suits bass lines
    // and soft leads, and reaches an octave below the squares (.frequency 32
    // Hz and up; notes from PSG_C1). On it, .duty picks the waveform: 0 (the
    // default) the first registered, 1 the second, and so on; with none
    // registered, a built-in triangle. .volume plays as the nearest of the
    // hardware's four levels (25%, 50%, 75% and 100% of 15), and .fade steps
    // between them; .slide is ignored (warns), as on the noise channel.
    // In this engine version it is refused like an invalid channel:
    // psg_play() skips the sound and psg_music_play() leaves the track out,
    // each warning that the wave channel is planned.
    PSG_WAVE SERVAL_PLANNED("the PSG wave channel, docs/audio.md#wave-channel") = 3,
};

// PsgSound.duty: a square wave's tone color, from thin and buzzy to full. 0
// (left out) means PSG_DUTY_50.
#define PSG_DUTY_12 1 // 12.5%
#define PSG_DUTY_25 2 // 25%
#define PSG_DUTY_50 3 // 50%, the default: a pure square wave
#define PSG_DUTY_75 4 // 75%, sounds like 25%

// One sound effect: a single tone, or a short melody of notes. Fields left out
// of an initializer take sensible defaults; a minimal sound needs only
// .frequency and .frames.
typedef struct {
    u8 channel;       // PSG_SQUARE1 (default), PSG_SQUARE2 or PSG_NOISE (PSG_WAVE is
                      // planned)
    u8 duty;          // squares: PSG_DUTY_*; 0 means PSG_DUTY_50. PSG_WAVE (planned):
                      // the waveform's number (psg_waves_set)
    u8 volume;        // starting volume 1-15; 0 means 15, or 0 (silence) for a sound
                      // that fades in, so it rises from silence to full volume
    s8 fade;          // volume envelope: -1 (fast) to -7 (slow) fades out, 1 (fast) to
                      // 7 (slow) fades in, 0 holds the volume
    s8 slide;         // PSG_SQUARE1 only: pitch slide, -1 (fast) to -7 (slow) down, 1 to
                      // 7 up, 0 none
    u8 slide_size;    // PSG_SQUARE1: how far each slide step moves, 1 (big) to 7
                      // (small); 0 means 1
    u16 frequency;    // pitch in Hz: squares 64 to 65535; noise 4 to 65535, higher is
                      // hissier (the noise channel's rates are coarse: the closest
                      // one is used); PSG_WAVE (planned) 32 to 65535
    u16 frames;       // how long it plays (each note, for a melody, where it is
                      // required); 0: until it fades out, or until replaced
    const u16* notes; // optional melody: note_count frequencies in Hz (0 = rest),
                      // played in turn instead of .frequency
    u8 note_count;
    u8 priority; // 0 (default) to 255: while this sound plays, sounds of lower
                 // priority on its channel are not played; equal or higher
                 // ones replace it. Music on the channel has the song's
                 // .priority (0 unless set)
} PsgSound;

// Registers the game's sound table: table[id] is the sound with that ID.
// Stops the sound effects playing (the music plays on).
void psg_table_set(const PsgSound* const* table, u16 count);

// Plays a sound, replacing whatever its channel was playing, unless that is a
// sound of higher priority still playing (then it does nothing). On a channel
// the music uses, the sound plays if its priority is at least the song's, and
// the music comes back on that channel when it ends.
void psg_play(u16 sound_id);

// Silences every PSG channel: sound effects and music. Tracker music and
// sampled effects (music_stop(), sfx_stop_all()) are unaffected.
void psg_stop_all(void);

// Registers the waveforms the wave channel (PSG_WAVE, planned) plays, for
// sound effects and songs alike: `count` waveforms of 32 4-bit steps, each 4
// words as wave RAM holds them. The steps play from the first word's lowest
// byte up, the high nibble of each byte first: a first word of 0x67452301
// plays 0, 1, 2, ... 7. A sound or track with .duty n plays waves[n]; a .duty
// of `count` or more plays waves[0] (warns). The table must stay valid while
// the wave channel plays from it (keep it const). count 0 goes back to the
// built-in triangle; a NULL or invalid `waves` with a count is ignored
// (warns). A new table takes effect from the wave channel's next note.
//
// Planned (docs/audio.md#wave-channel): in this engine version it ignores the
// table and warns once (debug builds); the wave channel doesn't play.
SERVAL_PLANNED("the PSG wave channel, docs/audio.md#wave-channel")
void psg_waves_set(const u32* waves, u8 count);

// --- PSG music -------------------------------------------------------------
//
// Chiptune songs on the tone generators: psg_music_*(), not to be confused
// with tracker music (music_*(), below), a separate player for modules from
// the sound bank. A song is one track of notes per channel, played in time
// with a tempo and looped. Notes are numbers: PSG_C4 is middle C, PSG_A4 440
// Hz, PSG_CS4 C sharp (D flat), and a note plus 12 is an octave up. Square
// channels play PSG_C2 and up; on the noise channel a note picks the noise
// rate closest to its pitch (low notes rumble, high ones hiss: drums).
// Example:
//
//     static const PsgNote lead[] = {{PSG_E4, 2}, {PSG_G4, 2}, {PSG_C5, 4}, {PSG_REST, 8}};
//     static const PsgNote beat[] = {{PSG_C3, 0}, {PSG_C7, 0}}; // 0: the track's .length
//     static const PsgTrack tracks[] = {
//         {.channel = PSG_SQUARE1, .notes = lead, .note_count = 4, .duty = PSG_DUTY_25},
//         {.channel = PSG_NOISE, .notes = beat, .note_count = 2, .length = 4, .fade = -1},
//     };
//     static const PsgSong tune = {.tempo = 140, .tracks = tracks, .track_count = 2};
//     psg_music_play(&tune);

// PsgNote.note: a rest, and the notes from C0 (16 Hz) to B10 (31.6 kHz).
// Square channels play C2 (65 Hz) and up; the wave channel (planned) will play
// C1 (33 Hz) and up.
#define PSG_REST 0
#define SERVAL_PSG_OCTAVE_(o)                                                                      \
    PSG_C##o = 12 * ((o) + 1), PSG_CS##o, PSG_D##o, PSG_DS##o, PSG_E##o, PSG_F##o, PSG_FS##o,      \
    PSG_G##o, PSG_GS##o, PSG_A##o, PSG_AS##o, PSG_B##o
enum {
    SERVAL_PSG_OCTAVE_(0),
    SERVAL_PSG_OCTAVE_(1),
    SERVAL_PSG_OCTAVE_(2),
    SERVAL_PSG_OCTAVE_(3),
    SERVAL_PSG_OCTAVE_(4),
    SERVAL_PSG_OCTAVE_(5),
    SERVAL_PSG_OCTAVE_(6),
    SERVAL_PSG_OCTAVE_(7),
    SERVAL_PSG_OCTAVE_(8),
    SERVAL_PSG_OCTAVE_(9),
    SERVAL_PSG_OCTAVE_(10),
};
#undef SERVAL_PSG_OCTAVE_

// PsgTrack.loop: play the track once, then fall silent.
#define PSG_NO_LOOP 0xFFFF

// One note of a track: PSG_REST or a note (PSG_C4 ...) held for .length
// ticks (0 means the track's .length).
typedef struct {
    u8 note;
    u8 length;
} PsgNote;

// The notes one channel plays, and how they sound.
typedef struct {
    u8 channel;           // PSG_SQUARE1 (default), PSG_SQUARE2 or PSG_NOISE
                          // (PSG_WAVE is planned)
    u8 duty;              // squares: PSG_DUTY_*; 0 means PSG_DUTY_50. PSG_WAVE
                          // (planned): the waveform's number (psg_waves_set)
    u8 volume;            // each note's starting volume 1-15, as in PsgSound
    s8 fade;              // each note's volume envelope, as in PsgSound
    u8 length;            // ticks of a note whose .length is 0; 0 means one beat
    const PsgNote* notes; // played in turn, then from notes[loop] again
    u16 note_count;
    u16 loop; // index of the note the track loops back to (0, the default: the
              // start); PSG_NO_LOOP plays it once
} PsgTrack;

// A song: up to one track per channel, played together. Each track loops on
// its own, so a short drum track can repeat under a longer melody.
typedef struct {
    u16 tempo;         // beats per minute; 0 means 120
    u8 ticks_per_beat; // note lengths are in ticks: 0 means 4 (a tick is a
                       // 16th note); a tick can't be shorter than a frame
    u8 priority;       // sound effects below this priority don't play on the
                       // music's channels (0, the default: every sound does)
    const PsgTrack* tracks;
    u8 track_count;
} PsgSong;

// Starts a song from the beginning at its own tempo, replacing the one
// playing (paused or not). Sound effects playing keep their channels; the
// music comes in on each channel when its sound ends. Advanced by frame_end().
// A NULL song, or one whose tracks are all invalid, plays nothing (warns);
// invalid tracks are left out (warns). Tracker music (music_play()) is a
// separate player and plays on.
void psg_music_play(const PsgSong* song);

// Stops the PSG music. Sound effects and tracker music keep playing.
void psg_music_stop(void);

// True while a song plays, paused or not: until psg_music_stop() or
// psg_stop_all(), or until every track of a song that doesn't loop has ended.
bool psg_music_playing(void);

// Pauses the music where it is: its time stands still and its channels go
// quiet. Sound effects play on, on every channel, whatever their priority.
// Nothing happens if no song plays or it is already paused.
void psg_music_pause(void);

// Resumes paused music exactly where it stopped: held notes start again at
// once, tracks that fade out come back with their next note. Nothing happens
// if the music isn't paused. psg_music_play(), psg_music_stop() and
// psg_stop_all() also end a pause.
void psg_music_resume(void);

// True while the music is paused (psg_music_playing() is true too).
bool psg_music_paused(void);

// Changes the tempo of the song playing, in beats per minute, from where it
// is: no jump, and it stays in time. 0 goes back to the song's own .tempo,
// which psg_music_play() also restores. Ignored if no song plays (warns).
void psg_music_set_tempo(u16 tempo);

// PSG music volume, 0 (silent) to 15 (the default: the tracks' own volumes):
// the tone generators' 16 steps, unlike music_set_volume()'s 0-255. It scales
// each note's starting volume, from each channel's next note on (a held note
// keeps its volume); sound effects are unaffected. Tracks that fade in rise
// to full volume regardless, unless the music volume is 0. Above 15: 15
// (warns).
void psg_music_set_volume(u8 volume);

// --- Tracker music and sampled sound effects (planned) ----------------------
//
// Modules (MOD, S3M, XM and IT files) and sampled sound effects (WAV files),
// mixed in software into the two Direct Sound channels while the PSG plays
// on. Maxmod (the BlocksDS fork) will play them. A game's modules and samples
// are built into one sound bank by Maxmod's mmutil (Studio Advance runs it),
// which also numbers them from 0 in the header it generates: MOD_<file> for
// each module, SFX_<file> for each sample. The bank's format is that of the
// Maxmod the engine links, and is the engine's business: games register it
// whole (audio_bank_set()) and play by those numbers. A bank must be built by
// the mmutil matching the engine's Maxmod (docs/audio.md#sound-bank).
//
// Mixing costs CPU time for every channel playing, unlike the PSG; the
// engine's figures are measured when it is implemented (docs/audio.md has
// Maxmod's own). PSG music (psg_music_*() above) is a separate player.
//
// Everything here is planned (docs/releases.md#planned-api): in this engine
// version each function does nothing, returns false or SFX_NONE, and warns
// once in debug builds. On the web they will stay so after the GBA plays
// them, until the web has a player of its own (docs/audio.md#web).

// Registers the game's sound bank, the data mmutil built (in ROM, where it
// stays: it must stay valid while registered), and stops any tracker music
// and sampled effects playing. Call it once at startup, before music_play()
// and sfx_play(); registering another bank replaces it, NULL unregisters it.
// An invalid pointer is refused (warns), leaving no bank. The PSG is
// unaffected.
//
// Planned (docs/audio.md#sound-bank): in this engine version it ignores the
// bank and warns once (debug builds).
SERVAL_PLANNED("tracker music and sampled sound, docs/audio.md#sound-bank")
void audio_bank_set(const void* bank);

// Starts module `music_id` of the bank (a MOD_* number) from its beginning,
// replacing the module playing (paused or not). `loop` true plays it until
// music_stop(); false plays it once, then music_playing() turns false.
// Resets music_set_speed() to 100; music_set_volume() stays. Ignored (warns)
// without a bank, or for an ID the bank doesn't have. PSG music
// (psg_music_play()) is a separate player and plays on.
//
// Planned (docs/audio.md#tracker-music): in this engine version nothing plays
// (warns once, debug builds).
SERVAL_PLANNED("tracker music, docs/audio.md#tracker-music")
void music_play(u16 music_id, bool loop);

// Stops the tracker music. Sampled effects and the PSG play on. Nothing
// happens if no module plays.
//
// Planned: in this engine version it does nothing (warns once).
SERVAL_PLANNED("tracker music, docs/audio.md#tracker-music")
void music_stop(void);

// True while a module plays, paused or not: from music_play() until
// music_stop() or audio_bank_set(), or until a module played once ends.
//
// Planned: in this engine version it returns false (warns once).
SERVAL_PLANNED("tracker music, docs/audio.md#tracker-music")
bool music_playing(void);

// Pauses the tracker music where it is: its time stands still and it goes
// quiet. Nothing happens if no module plays or it is already paused.
//
// Planned: in this engine version it does nothing (warns once).
SERVAL_PLANNED("tracker music, docs/audio.md#tracker-music")
void music_pause(void);

// Resumes paused tracker music exactly where it stopped. Nothing happens if
// the music isn't paused. music_play(), music_stop() and audio_bank_set() also
// end a pause.
//
// Planned: in this engine version it does nothing (warns once).
SERVAL_PLANNED("tracker music, docs/audio.md#tracker-music")
void music_resume(void);

// True while the tracker music is paused (music_playing() is true too).
//
// Planned: in this engine version it returns false (warns once).
SERVAL_PLANNED("tracker music, docs/audio.md#tracker-music")
bool music_paused(void);

// Tracker music volume, 0 (silent) to 255 (the default: the module's own
// volumes), at once, for the module playing and the next. Finer than
// psg_music_set_volume()'s 0-15, so a fade of one step a frame is smooth.
// Sampled effects and the PSG are unaffected.
//
// Planned: in this engine version it does nothing (warns once).
SERVAL_PLANNED("tracker music, docs/audio.md#tracker-music")
void music_set_volume(u8 volume);

// Tracker music speed, in percent of the module's own tempo, from where it
// is: 100 as written, 50 half speed, 200 double; the pitch stays. 0 means
// 100; other values outside 50-200 are clamped (warns). music_play() resets
// it to 100. E.g. a hurry-up: music_set_speed(125). (PSG music has
// psg_music_set_tempo(), in beats per minute.)
//
// Planned: in this engine version it does nothing (warns once).
SERVAL_PLANNED("tracker music, docs/audio.md#tracker-music")
void music_set_speed(u16 percent);

// A sampled effect playing, from sfx_play(): a handle, like Entity, that goes
// stale when the effect ends or is stopped (then sfx_playing() is false and
// sfx_stop() does nothing). Generational, so a stale handle never stops a
// later effect that took its channel. Not an effect's ID: IDs number the
// bank's samples (SFX_* in mmutil's header, from 0), a handle names one
// playing of one.
typedef u16 Sfx;

// Never refers to an effect: what sfx_play() and sfx_play_ex() return when
// nothing played, and a safe initial value for an Sfx. Not planned itself
// (the planned functions already return it). No sample may be named "none":
// mmutil's header would define SFX_NONE for it too.
#define SFX_NONE ((Sfx)0)

// Plays sample `sfx_id` of the bank (an SFX_* number) as an effect, at full
// volume, centred, at its recorded pitch and with priority 0: sfx_play_ex(id,
// 255, 0, FX_ONE, 0). Returns its handle, or SFX_NONE if it didn't play: no
// bank or an ID the bank doesn't have (both warn), or no mixer channel free
// and every effect playing of higher priority (see sfx_play_ex).
//
// Planned (docs/audio.md#sampled-sound-effects): in this engine version
// nothing plays; it returns SFX_NONE (warns once, debug builds).
SERVAL_PLANNED("sampled sound effects, docs/audio.md#sampled-sound-effects")
Sfx sfx_play(u16 sfx_id);

// Like sfx_play(), with:
// - volume: 0 (silent) to 255 (full);
// - pan: -128 (left) to 127 (right), 0 centred;
// - pitch: a FIXED factor of the recorded pitch (fixed.h): FX_ONE as
//   recorded, FX(2) an octave up, FX_ONE / 2 an octave down. 0 means FX_ONE;
//   values outside FX_ONE / 16 to FX(16) are clamped (warns);
// - priority: 0 to 255. When no mixer channel is free (the music's notes and
//   the effects share them), the playing effect of lowest priority stops for
//   this one if this one's priority is at least as high (as PsgSound.priority
//   does); otherwise this one doesn't play.
// An effect whose sample loops (loop points set in the sample) plays until
// sfx_stop() or sfx_stop_all(). Returns its handle, or SFX_NONE.
//
// Planned: in this engine version nothing plays; it returns SFX_NONE (warns
// once).
SERVAL_PLANNED("sampled sound effects, docs/audio.md#sampled-sound-effects")
Sfx sfx_play_ex(u16 sfx_id, u8 volume, s8 pan, FIXED pitch, u8 priority);

// Stops an effect at once. Nothing happens for SFX_NONE or a stale handle.
//
// Planned: in this engine version it does nothing (warns once).
SERVAL_PLANNED("sampled sound effects, docs/audio.md#sampled-sound-effects")
void sfx_stop(Sfx sfx);

// True while the effect plays; false for SFX_NONE and stale handles.
//
// Planned: in this engine version it returns false (warns once).
SERVAL_PLANNED("sampled sound effects, docs/audio.md#sampled-sound-effects")
bool sfx_playing(Sfx sfx);

// Stops every sampled effect. The tracker music and the PSG play on.
//
// Planned: in this engine version it does nothing (warns once).
SERVAL_PLANNED("sampled sound effects, docs/audio.md#sampled-sound-effects")
void sfx_stop_all(void);

// Volume of all sampled effects, 0 (silent) to 255 (the default: each
// effect's own), at once, for playing effects too: an options menu's "sound
// volume". The tracker music and the PSG are unaffected.
//
// Planned: in this engine version it does nothing (warns once).
SERVAL_PLANNED("sampled sound effects, docs/audio.md#sampled-sound-effects")
void sfx_set_volume(u8 volume);

#endif // SERVAL_AUDIO_H
