#ifndef SERVAL_AUDIO_H
#define SERVAL_AUDIO_H

// Sound. See docs/audio.md.
//
// So far: sound effects on the GBA's tone generators ("PSG": two square waves
// and a noise channel), which cost no CPU to play. Ideal for bleeps, hits,
// jumps, pickups and short jingles. Tracker music and sampled sound effects
// (Maxmod) are planned.
//
// Like sprites, sounds are constant tables (normally generated by Studio
// Advance) registered with psg_table_set(), and played by ID.

#include "serval/platform.h"

// PsgSound.channel. Each channel plays one sound at a time; playing a new
// sound on a busy channel replaces the old one.
#define PSG_SQUARE1 0 // square wave that can also slide in pitch (PsgSound.slide)
#define PSG_SQUARE2 1 // square wave
#define PSG_NOISE 2   // noise: hits, explosions, drums

// PsgSound.duty: a square wave's tone color, from thin and buzzy to full.
#define PSG_DUTY_12 0 // 12.5%
#define PSG_DUTY_25 1 // 25%
#define PSG_DUTY_50 2 // 50%, the default: a pure square wave
#define PSG_DUTY_75 3 // 75%, sounds like 25%

// One sound effect: a single tone, or a short melody of notes. Fields left out
// of an initializer take sensible defaults; a minimal sound needs only
// .frequency and .frames.
typedef struct {
    u8 channel;       // PSG_SQUARE1 (default), PSG_SQUARE2 or PSG_NOISE
    u8 duty;          // squares: PSG_DUTY_*; 0 means PSG_DUTY_50 like the default
    u8 volume;        // starting volume 1-15; 0 means 15
    s8 fade;          // volume envelope: -1 (fast) to -7 (slow) fades out, 1 (fast) to
                      // 7 (slow) fades in, 0 holds the volume
    s8 slide;         // PSG_SQUARE1 only: pitch slide, -1 (fast) to -7 (slow) down, 1 to
                      // 7 up, 0 none
    u8 slide_size;    // PSG_SQUARE1: how far each slide step moves, 1 (big) to 7
                      // (small); 0 means 1
    u16 frequency;    // pitch in Hz (64 to 131072; noise: roughly 2 to 524288,
                      // higher is hissier)
    u16 frames;       // how long it plays (each note, for a melody); 0: until it
                      // fades out, or until replaced
    const u16* notes; // optional melody: note_count frequencies in Hz (0 = rest),
                      // played in turn instead of .frequency
    u8 note_count;
} PsgSound;

// Registers the game's sound table: table[id] is the sound with that ID.
// Stops all sounds.
void psg_table_set(const PsgSound* const* table, u16 count);

// Plays a sound, replacing whatever its channel was playing.
void psg_play(u16 sound_id);

// Silences every PSG channel.
void psg_stop_all(void);

#endif // SERVAL_AUDIO_H
