#ifndef SERVAL_AUDIO_H
#define SERVAL_AUDIO_H

// Sound. See docs/audio.md.
//
// So far: sound effects and chiptune music on the GBA's tone generators
// ("PSG": two square waves and a noise channel), which cost almost no CPU to
// play. Sound effects suit bleeps, hits, jumps, pickups and short jingles;
// songs (PsgSong) play looping tunes of notes on the same channels, and sound
// effects take a channel over while they play. Tracker music and sampled sound
// effects (Maxmod) are planned.
//
// Like sprites, sounds are constant tables (normally generated by Studio
// Advance) registered with psg_table_set(), and played by ID.

#include "serval/platform.h"

// PsgSound.channel and PsgTrack.channel. Each channel plays one sound at a
// time; playing a new sound on a busy channel replaces the old one unless the
// old one has a higher .priority.
#define PSG_SQUARE1 0 // square wave that can also slide in pitch (PsgSound.slide)
#define PSG_SQUARE2 1 // square wave
#define PSG_NOISE 2   // noise: hits, explosions, drums

// PsgSound.duty: a square wave's tone color, from thin and buzzy to full. 0
// (left out) means PSG_DUTY_50.
#define PSG_DUTY_12 1 // 12.5%
#define PSG_DUTY_25 2 // 25%
#define PSG_DUTY_50 3 // 50%, the default: a pure square wave
#define PSG_DUTY_75 4 // 75%, sounds like 25%

// One sound effect: a single tone, or a short melody of notes. Fields left out
// of an initializer take sensible defaults; a minimal sound needs only
// .frequency and .frames.
typedef struct {
    u8 channel;       // PSG_SQUARE1 (default), PSG_SQUARE2 or PSG_NOISE
    u8 duty;          // squares: PSG_DUTY_*; 0 means PSG_DUTY_50
    u8 volume;        // starting volume 1-15; 0 means 15, or 0 (silence) for a sound
                      // that fades in, so it rises from silence to full volume
    s8 fade;          // volume envelope: -1 (fast) to -7 (slow) fades out, 1 (fast) to
                      // 7 (slow) fades in, 0 holds the volume
    s8 slide;         // PSG_SQUARE1 only: pitch slide, -1 (fast) to -7 (slow) down, 1 to
                      // 7 up, 0 none
    u8 slide_size;    // PSG_SQUARE1: how far each slide step moves, 1 (big) to 7
                      // (small); 0 means 1
    u16 frequency;    // pitch in Hz: squares 64 to 65535; noise 4 to 65535, higher is
                      // hissier (the noise channel's rates are coarse: the closest
                      // one is used)
    u16 frames;       // how long it plays (each note, for a melody, where it is
                      // required); 0: until it fades out, or until replaced
    const u16* notes; // optional melody: note_count frequencies in Hz (0 = rest),
                      // played in turn instead of .frequency
    u8 note_count;
    u8 priority; // 0 (default) to 255: while this sound plays, sounds of lower
                 // priority on its channel are not played; equal or higher
                 // ones replace it. Music on the channel has the song's
                 // .priority (0 unless set)
} PsgSound;

// Registers the game's sound table: table[id] is the sound with that ID.
// Stops the sound effects playing (the music plays on).
void psg_table_set(const PsgSound* const* table, u16 count);

// Plays a sound, replacing whatever its channel was playing, unless that is a
// sound of higher priority still playing (then it does nothing). On a channel
// the music uses, the sound plays if its priority is at least the song's, and
// the music comes back on that channel when it ends.
void psg_play(u16 sound_id);

// Silences every PSG channel: sound effects and music.
void psg_stop_all(void);

// --- Music ---------------------------------------------------------------
//
// A song is one track of notes per channel, played in time with a tempo and
// looped. Notes are numbers: PSG_C4 is middle C, PSG_A4 440 Hz, PSG_CS4 C
// sharp (D flat), and a note plus 12 is an octave up. Square channels play
// PSG_C2 and up; on the noise channel a note picks the noise rate closest to
// its pitch (low notes rumble, high ones hiss: drums). Example:
//
//     static const PsgNote lead[] = {{PSG_E4, 2}, {PSG_G4, 2}, {PSG_C5, 4}, {PSG_REST, 8}};
//     static const PsgNote beat[] = {{PSG_C3, 0}, {PSG_C7, 0}}; // 0: the track's .length
//     static const PsgTrack tracks[] = {
//         {.channel = PSG_SQUARE1, .notes = lead, .note_count = 4, .duty = PSG_DUTY_25},
//         {.channel = PSG_NOISE, .notes = beat, .note_count = 2, .length = 4, .fade = -1},
//     };
//     static const PsgSong tune = {.tempo = 140, .tracks = tracks, .track_count = 2};
//     psg_music_play(&tune);

// PsgNote.note: a rest, and the notes from C0 (16 Hz) to B10 (31.6 kHz).
// Square channels play C2 (65 Hz) and up.
#define PSG_REST 0
#define SERVAL_PSG_OCTAVE_(o)                                                                      \
    PSG_C##o = 12 * ((o) + 1), PSG_CS##o, PSG_D##o, PSG_DS##o, PSG_E##o, PSG_F##o, PSG_FS##o,      \
    PSG_G##o, PSG_GS##o, PSG_A##o, PSG_AS##o, PSG_B##o
enum {
    SERVAL_PSG_OCTAVE_(0),
    SERVAL_PSG_OCTAVE_(1),
    SERVAL_PSG_OCTAVE_(2),
    SERVAL_PSG_OCTAVE_(3),
    SERVAL_PSG_OCTAVE_(4),
    SERVAL_PSG_OCTAVE_(5),
    SERVAL_PSG_OCTAVE_(6),
    SERVAL_PSG_OCTAVE_(7),
    SERVAL_PSG_OCTAVE_(8),
    SERVAL_PSG_OCTAVE_(9),
    SERVAL_PSG_OCTAVE_(10),
};
#undef SERVAL_PSG_OCTAVE_

// PsgTrack.loop: play the track once, then fall silent.
#define PSG_NO_LOOP 0xFFFF

// One note of a track: PSG_REST or a note (PSG_C4 ...) held for .length
// ticks (0 means the track's .length).
typedef struct {
    u8 note;
    u8 length;
} PsgNote;

// The notes one channel plays, and how they sound.
typedef struct {
    u8 channel;           // PSG_SQUARE1 (default), PSG_SQUARE2 or PSG_NOISE
    u8 duty;              // squares: PSG_DUTY_*; 0 means PSG_DUTY_50
    u8 volume;            // each note's starting volume 1-15, as in PsgSound
    s8 fade;              // each note's volume envelope, as in PsgSound
    u8 length;            // ticks of a note whose .length is 0; 0 means one beat
    const PsgNote* notes; // played in turn, then from notes[loop] again
    u16 note_count;
    u16 loop; // index of the note the track loops back to (0, the default: the
              // start); PSG_NO_LOOP plays it once
} PsgTrack;

// A song: up to one track per channel, played together. Each track loops on
// its own, so a short drum track can repeat under a longer melody.
typedef struct {
    u16 tempo;         // beats per minute; 0 means 120
    u8 ticks_per_beat; // note lengths are in ticks: 0 means 4 (a tick is a
                       // 16th note); a tick can't be shorter than a frame
    u8 priority;       // sound effects below this priority don't play on the
                       // music's channels (0, the default: every sound does)
    const PsgTrack* tracks;
    u8 track_count;
} PsgSong;

// Starts a song from the beginning at its own tempo, replacing the one
// playing (paused or not). Sound effects playing keep their channels; the
// music comes in on each channel when its sound ends. Advanced by frame_end().
void psg_music_play(const PsgSong* song);

// Stops the music. Sound effects keep playing.
void psg_music_stop(void);

// True while a song plays, paused or not: until psg_music_stop() or
// psg_stop_all(), or until every track of a song that doesn't loop has ended.
bool psg_music_playing(void);

// Pauses the music where it is: its time stands still and its channels go
// quiet. Sound effects play on, on every channel, whatever their priority.
// Nothing happens if no song plays or it is already paused.
void psg_music_pause(void);

// Resumes paused music exactly where it stopped: held notes start again at
// once, tracks that fade out come back with their next note. Nothing happens
// if the music isn't paused. psg_music_play(), psg_music_stop() and
// psg_stop_all() also end a pause.
void psg_music_resume(void);

// True while the music is paused (psg_music_playing() is true too).
bool psg_music_paused(void);

// Changes the tempo of the song playing, in beats per minute, from where it
// is: no jump, and it stays in time. 0 goes back to the song's own .tempo,
// which psg_music_play() also restores. Ignored if no song plays (warns).
void psg_music_set_tempo(u16 tempo);

// Music volume, 0 (silent) to 15 (the default: the tracks' own volumes). It
// scales each note's starting volume, from each channel's next note on (a
// held note keeps its volume); sound effects are unaffected. Tracks that fade
// in rise to full volume regardless, unless the music volume is 0.
void psg_music_set_volume(u8 volume);

#endif // SERVAL_AUDIO_H
