#ifndef SERVAL_SPRITES_H
#define SERVAL_SPRITES_H

// Sprite assets, sprite groups and drawing. See docs/sprites.md.
//
// Sprite data lives in ROM as constant tables, normally generated by Studio
// Advance's build. Games refer to sprites by ID: an index into the sprite table
// registered with sprite_table_set(). A sprite can be drawn once a group
// containing it has been loaded into VRAM.
//
// Some names here are planned (SERVAL_PLANNED, docs/releases.md#planned-api):
// declared so that games and tools can target them, implemented in a later
// 1.x version. Each one's comment says what it will do and what it does now.

#include "serval/fixed.h"
#include "serval/platform.h"
#include "serval/screen.h" // Color, for sprite_set_colors()

// SpriteAsset.size: the sprite's dimensions in pixels (width x height). These
// are the sizes the hardware supports.
#define SPRITE_8x8 1
#define SPRITE_16x16 2
#define SPRITE_32x32 3
#define SPRITE_64x64 4
#define SPRITE_16x8 5
#define SPRITE_32x8 6
#define SPRITE_32x16 7
#define SPRITE_64x32 8
#define SPRITE_8x16 9
#define SPRITE_8x32 10
#define SPRITE_16x32 11
#define SPRITE_32x64 12

// SpriteAsset.flags, combinable with |. sprite_group_load() refuses a group
// with a sprite that has any other bit set (warning in debug builds): bits 0
// and 4-7 are reserved for later versions. (Bit 0 was SPRITE_ASSET_STREAMED
// before 1.0; streaming is a group's choice: SPRITE_GROUP_STREAMED.)
#define SPRITE_ASSET_METASPRITE (1 << 1) // made of other sprites: .pieces (SpritePiece below)
#define SPRITE_ASSET_ANIM_ONCE                                                                     \
    (1 << 2) // sys_animate stops on the last frame (or frame_order
             // step) instead of looping
enum {
    // Planned: .tiles holds the sprite's frame_count x tiles_per_frame tiles
    // LZ77-compressed, as the GBA BIOS's LZ77UnCompVram reads them (type
    // 0x10: a header word with the unpacked size in bytes, which must be
    // frame_count x tiles_per_frame x 32; compressors call this their
    // VRAM-safe mode). They are unpacked into VRAM when the group loads, so
    // the sprite takes less ROM and the same VRAM. Ordinary sprites in
    // resident groups only: a metasprite with it, or a streamed group holding
    // such a sprite (streaming copies frames straight from ROM), will be
    // refused. Until implemented, sprite_group_load() refuses a group holding
    // a sprite with this flag (returns false, warning in debug builds).
    SPRITE_ASSET_LZ77 SERVAL_PLANNED("LZ77-compressed sprites, docs/sprites.md#lz77-compression") =
        1 << 3,
};

// SpriteAsset.frame_order entries: a frame index (0-63), optionally drawn
// flipped, e.g. {0, 1, 2, 1 | SPRITE_FRAME_FLIP_H}.
#define SPRITE_FRAME_FLIP_H (1 << 6)
#define SPRITE_FRAME_FLIP_V (1 << 7)

// One piece of a metasprite: a frame of another sprite, placed by its center
// relative to the metasprite's pivot, the point drawn at (x, y) - origin. Rotating or
// scaling the metasprite turns and scales the pieces' positions about the
// pivot, and each piece with them, so the pivot can be anywhere: a gun's
// mount, a door's hinge, a card's center. The pieces' own origins are
// ignored. Pieces are drawn in order, the first in front.
typedef struct {
    s16 x, y;   // the piece's center, relative to the pivot (unflipped, unrotated)
    u16 sprite; // sprite ID of an ordinary sprite (not a metasprite)
    u16 flags;  // for this piece: SPRITE_FLIP_H, SPRITE_FLIP_V, SPRITE_PALETTE(n) and
                // SPRITE_BLEND, a subset of the draw flags below. Anything
                // else (a layer, SPRITE_HIDDEN, ...: those are the whole draw's) makes
                // sprite_group_load() refuse the metasprite's group (warns)
    u8 frame;   // the frame of that sprite
    // (One byte of padding follows on the GBA: reserved, leave it zero.)
} SpritePiece;

// A sprite: its pixels and how to draw them. Fields left out of an
// initializer take sensible defaults; only .size and .tiles are required.
//
// A metasprite (flags SPRITE_ASSET_METASPRITE) is drawn, rotated, scaled,
// flipped, animated and depth-sorted as one sprite, but made of others: its
// .pieces take the place of .tiles, .piece_count that of .tiles_per_frame,
// and .size is not used. Frame f is pieces[f * piece_count] to
// pieces[f * piece_count + piece_count - 1]. Its group needs no VRAM for it;
// the sprites its pieces use must be loaded (in its group or another) to be
// drawn. Each piece takes a hardware sprite; pieces sharing flips share a
// rotation matrix.
typedef struct {
    union {
        const u32* tiles;          // pixel data: 8x8 tiles of 4 bits per pixel, 8 words each,
                                   // frame after frame (each frame row by row, tile by tile)
        const SpritePiece* pieces; // metasprites: piece_count pieces per frame
    };
    u8 size; // SPRITE_16x16 etc. (required, except for metasprites)
    union {
        u8 tiles_per_frame; // 0: computed from size (the usual case); if set, at least
                            // what the size needs (more leaves padding between frames)
        u8 piece_count;     // metasprites: pieces per frame (at least 1)
    };
    u8 frame_count;        // animation frames; 0 means 1
    u8 order_length;       // frame_order entries (steps); at least 1 if frame_order is set
                           // (0 ignores it); nonzero without a frame_order: nothing plays
    u8 palette_slot;       // which of its group's palettes it uses
    s8 origin_x, origin_y; // drawn position = (x, y) - origin (metasprites: where the
                           // pivot is drawn; negative puts it right of / below (x, y))
    u8 flags;              // SPRITE_ASSET_*
    const u8* frame_times; // animation timing for sys_animate (ecs.h): how many frames
                           // (1/60 s) each animation frame shows, frame_count entries
                           // (order_length with frame_order); 0 holds that frame.
                           // NULL: every frame shows for one frame
    const u8* frame_order; // the animation sys_animate plays: frame indices, each with
                           // optional SPRITE_FRAME_FLIP_H/V, so frames can repeat, play
                           // backwards or mirrored without duplicate tiles. NULL: frames
                           // 0 to frame_count - 1 in order
} SpriteAsset;

// SpriteGroup.flags. sprite_group_load() refuses a group with any other bit
// set (warning in debug builds): bits 1-7 are reserved for later versions.
#define SPRITE_GROUP_RESIDENT 0 // all frames copied to VRAM on load (the default)
enum {
    // Planned: a streamed group. Its sprites keep their frames in ROM, and
    // each distinct frame drawn in a frame (sprite and frame number) takes
    // one of the group's .slots in VRAM, copied there in VBlank by
    // frame_end() unless it is there already, in the same VBlank as the OAM,
    // so it shows on time. Big, many-framed art (a boss, a character with
    // dozens of frames) then costs VRAM for the frames on screen, not for all
    // of them. Drawing is unchanged: sprite_draw*(), the render systems,
    // metasprite pieces and sys_animate work as with resident sprites.
    // Frames past the slots in one frame are not drawn (counted in
    // sprite_stats().dropped, warning in debug builds). Each new frame is a
    // copy in VBlank (about 64 cycles per tile), so keep it to a few new
    // frames per frame. Slots are taken from the top of sprite VRAM when the
    // group loads and freed with it. Until implemented, sprite_group_load()
    // refuses a group with this flag (returns false, warning in debug builds).
    SPRITE_GROUP_STREAMED SERVAL_PLANNED(
        "streamed sprite groups, docs/sprites.md#residency-modes") = 1 << 0,
};

// Sprites loaded and unloaded together, with the palettes they share.
typedef struct {
    const u16* sprite_ids; // IDs (sprite table indices) of its sprites; NULL means
                           // IDs 0 to sprite_count - 1
    const u16* palettes;   // palette_count banks of 16 colors (color 0 transparent)
    u8 sprite_count;
    u8 palette_count;
    u8 flags; // SPRITE_GROUP_* (0: resident)
    u8 slots; // SPRITE_GROUP_STREAMED (planned): how many distinct frames of its sprites
              // can be on screen at once, each slot the size of the group's largest frame;
              // 0 means 1. Must be 0 in a resident group (refused otherwise, warns)
} SpriteGroup;

// Most sprite IDs a sprite table may hold.
#define SPRITE_MAX 512

// sprite_draw() flags, combinable with |: flips, a layer, SPRITE_HIDDEN,
// SPRITE_PALETTE(n) and SPRITE_BLEND below. The same 16 bits are the
// entities' spr_flags (ecs.h), which add SPRITE_ANIM_FLIP_H/V, SPRITE_SCALED
// and SPRITE_SCREEN. Every bit has an owner; bits 13 and 14 are reserved.
#define SPRITE_FLIP_H (1 << 0)
#define SPRITE_FLIP_V (1 << 1)

// Layering, one of these at most. The screen's layers, front to back, are the
// HUD (background 0, where text.h draws), the foreground (background 1),
// sprites, the playfield (background 2) and the background (background 3); see
// docs/tilemaps.md. By default a sprite sits between the foreground and the
// playfield, so HUD text always stays readable. Among sprites on the same
// layer, the one drawn first is in front.
#define SPRITE_ABOVE_FOREGROUND (3 << 2) // above the foreground, still below the HUD
#define SPRITE_ABOVE_HUD (2 << 2)        // above everything
#define SPRITE_BEHIND_PLAYFIELD (1 << 2) // behind the playfield, above the background

// Not drawn at all, e.g. to make an entity blink by toggling it in spr_flags.
// The sprite keeps its place in the game; it just takes no hardware sprite.
#define SPRITE_HIDDEN (1 << 4)

// Set in spr_flags (ecs.h) by sys_animate: the flips that come from the
// current frame_order step, on top of the game's (XORed with them). Drawing
// ignores these two bits.
#define SPRITE_ANIM_FLIP_H (1 << 5)
#define SPRITE_ANIM_FLIP_V (1 << 6)

// For entities (spr_flags): drawn scaled by spr_scale (ecs.h), like
// sprite_draw_ex() with that scale on both axes. A flag rather than a nonzero
// spr_scale, so the render systems test it with the other flags and sprites
// without it don't pay for scaling (debug builds warn about a spr_scale set
// without it). sprite_draw() and its variants ignore it.
#define SPRITE_SCALED (1 << 7)

// For entities (spr_flags): drawn at the entity's position on the screen, not
// at its world position minus the camera, so it stays put while the camera
// scrolls the map (a shooter's ship, enemies and bullets; a HUD icon).
// sprite_draw() always takes screen coordinates and ignores it. Body tests
// follow it: for a pair of one screen-space and one world entity,
// body_overlap() and body_hit_side() (physics.h), and so vm_collide(), add the
// camera to the screen-space one's position and judge the pair in the world.
#define SPRITE_SCREEN (1 << 15)

// Draws the sprite with palette n (0-14) of its sprite group instead of its
// own (SpriteAsset.palette_slot), e.g. a white hit flash or another color of
// the same art: SPRITE_PALETTE(2). No SPRITE_PALETTE: the sprite's own
// palette. In spr_flags and sprite_draw*() flags. A
// palette the group doesn't have draws with the sprite's own (warning in
// debug builds). To change it on an entity:
// spr_flags[i] = (spr_flags[i] & ~SPRITE_PALETTE_MASK) | SPRITE_PALETTE(n).
// (n = 15 does not exist: it would spill into SPRITE_BLEND's bit.)
#define SPRITE_PALETTE(n) ((u16)(((n) + 1) << 8))
#define SPRITE_PALETTE_MASK (15u << 8)

// Bits 12-14 of the draw flags (sprite_draw*() flags, spr_flags and
// SpritePiece.flags) are the engine's: bit 12 is SPRITE_BLEND, and 13 and 14
// are reserved for later draw flags (mosaic and the object window). Games
// must not store anything in them: drawing doesn't check them (it is the hot
// path), so a stray bit is ignored today and gets a meaning in a later
// version. (SpritePiece.flags are checked at load: see SpritePiece.)
enum {
    // Drawn semi-transparent (the hardware's semi-transparent sprite mode).
    // Where the sprite is drawn over one of the `bottom` layers of
    // screen_set_blend() (screen.h), it is mixed with them with that call's
    // weights, whether or not its `top` layers include the sprites;
    // elsewhere, and while blending is off (the default) or paused (the
    // brightness is not 0), it is drawn opaque. For shadows, ghosts, glass.
    // In sprite_draw*() flags, spr_flags and SpritePiece.flags (a
    // metasprite's piece blends when the draw or the piece has it). The
    // render systems draw these sprites on their out-of-line path, as they do
    // SPRITE_PALETTE ones (about 110 cycles more per sprite; sprites without
    // either pay nothing).
    SPRITE_BLEND = 1 << 12,
};

// Registers the game's sprite table: table[id] is the sprite with that ID.
// The table and the sprites it points to must stay valid while it is
// registered (normally they are const data in ROM). Unloads all sprite groups
// and forgets every mark, as sprite_groups_reset() does.
void sprite_table_set(const SpriteAsset* const* table, u16 count);

// Copies a group's tiles and palettes to VRAM so its sprites can be drawn,
// after the groups loaded before it: tiles in sprite VRAM (1024 tiles of 4bpp
// 8x8) and each of its palettes in the next free sprite palette bank (16).
// Copies at once, so load while changing rooms (e.g. while the screen is
// faded out): a sprite drawn this frame from tiles being replaced may tear
// for a frame. The group itself need not stay valid afterwards; the sprite
// table must. A sprite already loaded (its ID in another loaded group, or the
// same group loaded twice) is drawn from the newest copy.
//
// Returns false, leaving nothing loaded from this group (warning in debug
// builds), if sprite VRAM or palette banks would run out, its data is
// incomplete (a sprite ID not in the sprite table, a NULL or invalid .tiles,
// .pieces or .palettes, no .size, a tiles_per_frame smaller than the size
// needs, a palette_slot past palette_count, a metasprite piece naming a
// missing sprite or frame), it has a value this version doesn't know (a
// .size past 12, a reserved bit in SpriteGroup.flags, SpriteAsset.flags or a
// piece's flags; nonzero .slots in a resident group), or it needs a planned
// feature (SPRITE_GROUP_STREAMED, SPRITE_ASSET_LZ77).
bool sprite_group_load(const SpriteGroup* group);

// Unloads every sprite group, freeing all sprite VRAM and palette banks, and
// forgets every mark (sprite_groups_mark()).
void sprite_groups_reset(void);

// --- Loading in layers: marks ---
//
// Groups load one after another (sprite_group_load()), and a mark is a point
// in that order. For room changes: load what every room uses (the player, the
// HUD, effects) once, take a mark, and release to it before loading each
// room's groups, so the room's VRAM and palette banks are reused and the
// shared groups stay:
//
//     sprite_group_load(&common);
//     u32 common_mark = sprite_groups_mark();
//     ...
//     sprite_groups_release(common_mark); // on every room change
//     sprite_group_load(&room_group);

// Returns a mark: an opaque value naming the point after the groups loaded
// so far, for sprite_groups_release(). Taken again before anything more
// loads, it returns the same mark. Marks nest: a mark taken after more loads
// is a new one, kept with the earlier ones, up to 16 of them; past that it
// returns the newest one (warning in debug builds), so releasing to it also
// unloads the groups loaded since that one was taken.
u32 sprite_groups_mark(void);

// Unloads every group loaded since `mark` was taken, keeping the groups
// loaded before it: their sprites are no longer loaded (drawing them does
// nothing, with a warning in debug builds, until a group with them loads
// again), and their sprite VRAM and palette banks go to the next loads.
// Takes effect at once, like sprite_group_load(). The marks taken after
// `mark` are forgotten; `mark` itself stays valid, so a game releases to the
// same mark on every room change. Ignored (warning in debug builds) for a
// value that isn't a current mark: one forgotten by releasing to an earlier
// mark, one from before the last sprite_groups_reset() or sprite_table_set(),
// or one sprite_groups_mark() never returned. A sprite ID loaded both before
// and after the mark is drawn from the newest copy, so releasing unloads it:
// keep each sprite in one group.
void sprite_groups_release(u32 mark);

// Draws a frame of a sprite this frame. Does nothing if the sprite is not
// loaded, the frame does not exist, it is fully off screen, or all hardware
// sprites are used. A metasprite draws its pieces around its pivot ((x, y)
// minus its origin), flipped as a
// whole by SPRITE_FLIP_H/V (positions and pieces), each piece with the
// flags' layer and SPRITE_PALETTE (or its own palette if the flags have
// none); pieces off screen or past the 128th hardware sprite are skipped one
// by one.
void sprite_draw(u16 sprite_id, u8 frame, int x, int y, u16 flags);

// Like sprite_draw, rotated around the sprite's center by `angle` (math.h
// angles: ANGLE_DEG(90) is a quarter turn clockwise). Art drawn facing right
// then faces (fx_cos(angle), fx_sin(angle)). The hardware has 32 rotation
// matrices per frame, shared by sprites with the same angle and flips; give
// many sprites few distinct angles. Past 32, sprites are drawn unrotated
// (reported in debug builds). Sprites that are off screen or not drawn take no
// matrix, and angle 0 draws exactly like sprite_draw (no matrix).
void sprite_draw_rotated(u16 sprite_id, u8 frame, int x, int y, u16 angle, u16 flags);

// Like sprite_draw_rotated, also scaled around the sprite's center: scale_x
// and scale_y are FIXED factors along the art's own axes (FX_ONE is normal
// size, FX(2) twice as big, FX_ONE / 2 half; negative mirrors along that
// axis, so a card flip runs scale_x from FX_ONE through 0 to -FX_ONE). A
// scale of 0 draws nothing. Scales of +-128 (FX(128)) or beyond are limited
// to just inside it, +-32767/256 (warning in debug builds). Shares the 32
// matrices with sprite_draw_rotated: draws with the same angle, flips and
// scales share one, so animate a scale in a few steps rather than giving
// every sprite its own.
//
// The hardware draws a rotated or enlarged sprite inside a box twice its size
// (double-size mode), centered on it: art that grows past that box is cut
// off (beyond scale 2 unrotated, about 1.4 at 45 degrees). Sprites that are
// only shrunk or mirrored (angle 0, scales within +-FX_ONE) are drawn in
// their own box, which costs half the scanline time of a rotated one. With
// no rotation and both scales FX_ONE it draws exactly like sprite_draw.
void sprite_draw_ex(u16 sprite_id, u8 frame, int x, int y, u16 angle, FIXED scale_x, FIXED scale_y,
                    u16 flags);

// What the hardware sprites did in the last frame (counted between
// frame_begin() and frame_end(); zero before the first frame_end()).
typedef struct {
    u16 drawn;         // hardware sprites used, of 128
    u16 matrices;      // rotation/scale matrices used, of 32
    u16 dropped;       // draws not shown because all 128 hardware sprites were used
    u16 untransformed; // rotated or scaled draws shown plain: all 32 matrices were used
    // With sprite_stats_scanlines(true), else 0:
    u16 cut_short;    // sprites missing from a scanline whose sprite time ran out
    u16 busiest_line; // sprite time the busiest scanline asked for, in cycles (of 1,210)
} SpriteStats;

// The last frame's sprite counts: how close a game runs to the hardware's
// limits, and what it lost past them, in release builds too (debug builds
// also warn once per problem).
SpriteStats sprite_stats(void);

// Makes frame_end() also work out the per-scanline sprite budget (off by
// default): the hardware has about 1,210 cycles a scanline to draw sprites,
// takes them in OAM order (the order they were drawn: the first in front)
// and skips what doesn't fit, so too many sprites on one line make the last
// ones vanish or cut off there. An ordinary sprite costs its width, a rotated
// or scaled one 10 + 2 x its box's width (the double-size box: 74 for a
// 16x16 rotated sprite, 266 for a 64x64 one); sprites entirely off screen
// cost nothing. sprite_stats() then reports the sprites that lost a line
// (cut_short) and the demand of the busiest line. It walks every scanline of
// every sprite drawn, a few thousand cycles a frame for a busy screen,
// counted in frame_cpu_cycles(): a tool for finding the problem, e.g. in a
// debug readout, not for every frame of a finished game.
void sprite_stats_scanlines(bool on);

// --- Changing a loaded sprite ---

// Replaces the pixels of frame `frame` of a loaded sprite with
// tiles_per_frame tiles from `tiles` (8 words each, as in SpriteAsset.tiles),
// e.g. a card face composed at run time into a RAM buffer and drawn as one
// hardware sprite. Every draw of that frame changes, from the frame after the
// copy: it happens in VBlank at the next frame_end(), so `tiles` must stay
// valid until then (a buffer composed for one sprite can't be reused for
// another in the same frame). Up to SPRITE_MAX_TILE_UPDATES calls per frame;
// a later call for the same sprite and frame replaces the earlier one. Each
// copy takes about 75 cycles of VBlank a tile from EWRAM (a 32x64 frame, 32
// tiles: about 2,400), so keep it to a few frames per frame. Ignored (warning
// in debug builds) for a sprite that isn't loaded, a metasprite (set its
// pieces' sprites' tiles instead), a sprite of a streamed group, a frame the
// sprite doesn't have, a NULL `tiles`, or a full queue.
// sprite_groups_release() and sprite_groups_reset() drop the copies queued
// for the sprites they unload. The VRAM for frames composed later comes from
// loading sprites whose .tiles are a blank frame in RAM, which they can all
// share (each sprite ID gets its own copy in VRAM). The mirror of
// tileset_set_tiles() (map.h) for sprites.
void sprite_set_tiles(u16 sprite_id, u8 frame, const u32* tiles);
enum {
    // sprite_set_tiles() calls queued per frame.
    SPRITE_MAX_TILE_UPDATES = 8,
};

// Changes `count` colors of the palettes of the group `sprite_id` was loaded
// with, from color `index` on: index = palette * 16 + color, with
// palettes numbered as SPRITE_PALETTE(n) numbers them (0 to the group's
// palette_count - 1), so one call can run across several of its palettes.
// For a hit flash, a palette cycle, colors faded with color_mix() (screen.h).
// The colors are copied at once (`colors` may be a temporary) into a shadow
// of the palettes, which reaches the screen in VBlank at the next
// frame_end(). Copy-on-write: the change belongs to that group's sprites
// only. A later version may share a bank between groups whose palettes are
// identical; writing to a shared bank then first gives the group its own copy
// of it, so the other groups keep their colors. If no free bank is left for
// that copy, the write goes to the shared bank and every group sharing it
// changes (warning in debug builds). Color 0 of each palette is transparent:
// a write to it is kept but not shown. The colors stay until changed again or
// the group is unloaded; to put the ROM colors back, write them again from the
// group's .palettes. Ignored (warning in debug builds) for a sprite that isn't
// loaded, a metasprite (its pieces' groups hold the colors), a NULL `colors`,
// or colors past the group's palettes (index + count > palette_count * 16).
// A count of 0 does nothing. A load in the same frame wins over earlier
// writes to its banks: sprite_group_load() writes its colors at once.
void sprite_set_colors(u16 sprite_id, u32 index, const Color* colors, u32 count);

#endif // SERVAL_SPRITES_H
