#ifndef SERVAL_SPRITES_H
#define SERVAL_SPRITES_H

// Sprite assets, sprite groups and drawing. See docs/sprites.md.
//
// Sprite data lives in ROM as constant tables, normally generated by Studio
// Advance's build. Games refer to sprites by ID: an index into the sprite table
// registered with sprite_table_set(). A sprite can be drawn once a group
// containing it has been loaded into VRAM.

#include "serval/fixed.h"
#include "serval/platform.h"

// SpriteAsset.size: the sprite's dimensions in pixels (width x height). These
// are the sizes the hardware supports.
#define SPRITE_8x8 1
#define SPRITE_16x16 2
#define SPRITE_32x32 3
#define SPRITE_64x64 4
#define SPRITE_16x8 5
#define SPRITE_32x8 6
#define SPRITE_32x16 7
#define SPRITE_64x32 8
#define SPRITE_8x16 9
#define SPRITE_8x32 10
#define SPRITE_16x32 11
#define SPRITE_32x64 12

// SpriteAsset.flags
#define SPRITE_ASSET_STREAMED (1 << 0)   // not supported yet
#define SPRITE_ASSET_METASPRITE (1 << 1) // not supported yet
#define SPRITE_ASSET_ANIM_ONCE                                                                     \
    (1 << 2) // sys_animate stops on the last frame (or
             // frame_order step) instead of looping

// SpriteAsset.frame_order entries: a frame index (0-63), optionally drawn
// flipped, e.g. {0, 1, 2, 1 | SPRITE_FRAME_FLIP_H}.
#define SPRITE_FRAME_FLIP_H (1 << 6)
#define SPRITE_FRAME_FLIP_V (1 << 7)

// A sprite: its pixels and how to draw them. Fields left out of an
// initializer take sensible defaults; only .size and .tiles are required.
typedef struct {
    const u32* tiles;      // pixel data: 8x8 tiles of 4 bits per pixel, 8 words each,
                           // frame after frame (each frame row by row, tile by tile)
    u8 size;               // SPRITE_16x16 etc. (required)
    u8 tiles_per_frame;    // 0: computed from size (the usual case); if set, at least
                           // what the size needs (more leaves padding between frames)
    u8 frame_count;        // animation frames; 0 means 1
    u8 order_length;       // frame_order entries (steps); at least 1 if frame_order is set
    u8 palette_slot;       // which of its group's palettes it uses
    s8 origin_x, origin_y; // drawn position = (x, y) - origin
    u8 flags;              // SPRITE_ASSET_*
    const u8* frame_times; // animation timing for sys_animate (ecs.h): how many frames
                           // (1/60 s) each animation frame shows, frame_count entries
                           // (order_length with frame_order); 0 holds that frame.
                           // NULL: every frame shows for one frame
    const u8* frame_order; // the animation sys_animate plays: frame indices, each with
                           // optional SPRITE_FRAME_FLIP_H/V, so frames can repeat, play
                           // backwards or mirrored without duplicate tiles. NULL: frames
                           // 0 to frame_count - 1 in order
} SpriteAsset;

// SpriteGroup.flags
#define SPRITE_GROUP_RESIDENT 0        // all frames copied to VRAM on load (the default)
#define SPRITE_GROUP_STREAMED (1 << 0) // not supported yet

// Sprites loaded and unloaded together, with the palettes they share.
typedef struct {
    const u16* sprite_ids; // IDs (sprite table indices) of its sprites; NULL means
                           // IDs 0 to sprite_count - 1
    const u16* palettes;   // palette_count banks of 16 colors (color 0 transparent)
    u8 sprite_count;
    u8 palette_count;
    u8 flags; // SPRITE_GROUP_*
} SpriteGroup;

// Most sprite IDs a sprite table may hold.
#define SPRITE_MAX 512

// sprite_draw() flags, combinable with |: flips, a layer, SPRITE_HIDDEN and
// SPRITE_PALETTE(n) below.
#define SPRITE_FLIP_H (1 << 0)
#define SPRITE_FLIP_V (1 << 1)

// Layering, one of these at most. The screen's layers, front to back, are the
// HUD (background 0, where text.h draws), the foreground (background 1),
// sprites, the playfield (background 2) and the background (background 3); see
// docs/tilemaps.md. By default a sprite sits between the foreground and the
// playfield, so HUD text always stays readable. Among sprites on the same
// layer, the one drawn first is in front.
#define SPRITE_ABOVE_FOREGROUND (3 << 2) // above the foreground, still below the HUD
#define SPRITE_ABOVE_HUD (2 << 2)        // above everything
#define SPRITE_BEHIND_PLAYFIELD (1 << 2) // behind the playfield, above the background

// Not drawn at all, e.g. to make an entity blink by toggling it in spr_flags.
// The sprite keeps its place in the game; it just takes no hardware sprite.
#define SPRITE_HIDDEN (1 << 4)

// Set in spr_flags (ecs.h) by sys_animate: the flips that come from the
// current frame_order step, on top of the game's (XORed with them). Drawing
// ignores these two bits.
#define SPRITE_ANIM_FLIP_H (1 << 5)
#define SPRITE_ANIM_FLIP_V (1 << 6)

// For entities (spr_flags): drawn scaled by spr_scale (ecs.h), like
// sprite_draw_ex() with that scale on both axes. A flag rather than a nonzero
// spr_scale, so the render systems test it with the other flags and sprites
// without it don't pay for scaling (debug builds warn about a spr_scale set
// without it). sprite_draw() and its variants ignore it.
#define SPRITE_SCALED (1 << 7)

// For entities (spr_flags): drawn at the entity's position on the screen, not
// at its world position minus the camera, so it stays put while the camera
// scrolls the map (a shooter's ship, enemies and bullets; a HUD icon).
// sprite_draw() always takes screen coordinates and ignores it. Only drawing
// changes: body_overlap() and body_hit_side() (physics.h) compare positions
// as stored, so against world entities the game adds the camera itself.
#define SPRITE_SCREEN (1 << 15)

// Draws the sprite with palette n (0-14) of its sprite group instead of its
// own (SpriteAsset.palette_slot), e.g. a white hit flash or another color of
// the same art: SPRITE_PALETTE(2). No SPRITE_PALETTE: the sprite's own
// palette. In spr_flags and sprite_draw()/sprite_draw_rotated() flags. A
// palette the group doesn't have draws with the sprite's own (warning in
// debug builds). To change it on an entity:
// spr_flags[i] = (spr_flags[i] & ~SPRITE_PALETTE_MASK) | SPRITE_PALETTE(n).
#define SPRITE_PALETTE(n) ((u16)(((n) + 1) << 8))
#define SPRITE_PALETTE_MASK (15u << 8)

// Registers the game's sprite table: table[id] is the sprite with that ID.
// Unloads all sprite groups.
void sprite_table_set(const SpriteAsset* const* table, u16 count);

// Copies a group's tiles and palettes to VRAM so its sprites can be drawn.
// Returns false, leaving nothing loaded from this group, if sprite VRAM or
// palette banks would run out, the group uses an unsupported feature, or its
// data is incomplete (e.g. a missing .tiles or .palettes; reported in debug
// builds).
bool sprite_group_load(const SpriteGroup* group);

// Unloads every sprite group, freeing all sprite VRAM and palette banks.
void sprite_groups_reset(void);

// Draws a frame of a sprite this frame. Does nothing if the sprite is not
// loaded, the frame does not exist, it is fully off screen, or all hardware
// sprites are used.
void sprite_draw(u16 sprite_id, u8 frame, int x, int y, u16 flags);

// Like sprite_draw, rotated around the sprite's center by `angle` (math.h
// angles: ANGLE_DEG(90) is a quarter turn clockwise). Art drawn facing right
// then faces (fx_cos(angle), fx_sin(angle)). The hardware has 32 rotation
// matrices per frame, shared by sprites with the same angle and flips; give
// many sprites few distinct angles. Past 32, sprites are drawn unrotated
// (reported in debug builds). Sprites that are off screen or not drawn take no
// matrix, and angle 0 draws exactly like sprite_draw (no matrix).
void sprite_draw_rotated(u16 sprite_id, u8 frame, int x, int y, u16 angle, u16 flags);

// Like sprite_draw_rotated, also scaled around the sprite's center: scale_x
// and scale_y are FIXED factors along the art's own axes (FX_ONE is normal
// size, FX(2) twice as big, FX_ONE / 2 half; negative mirrors along that
// axis, so a card flip runs scale_x from FX_ONE through 0 to -FX_ONE). A
// scale of 0 draws nothing. Scales beyond +-128 are limited to it (warning in
// debug builds). Shares the 32 matrices with sprite_draw_rotated: draws with
// the same angle, flips and scales share one, so animate a scale in a few
// steps rather than giving every sprite its own.
//
// The hardware draws a rotated or enlarged sprite inside a box twice its size
// (double-size mode), centered on it: art that grows past that box is cut
// off (beyond scale 2 unrotated, about 1.4 at 45 degrees). Sprites that are
// only shrunk or mirrored (angle 0, scales within +-FX_ONE) are drawn in
// their own box, which costs half the scanline time of a rotated one. With
// no rotation and both scales FX_ONE it draws exactly like sprite_draw.
void sprite_draw_ex(u16 sprite_id, u8 frame, int x, int y, u16 angle, FIXED scale_x, FIXED scale_y,
                    u16 flags);

// What the hardware sprites did in the last frame (counted between
// frame_begin() and frame_end(); zero before the first frame_end()).
typedef struct {
    u16 drawn;         // hardware sprites used, of 128
    u16 matrices;      // rotation/scale matrices used, of 32
    u16 dropped;       // draws not shown because all 128 hardware sprites were used
    u16 untransformed; // rotated or scaled draws shown plain: all 32 matrices were used
} SpriteStats;

// The last frame's sprite counts: how close a game runs to the hardware's
// limits, and what it lost past them, in release builds too (debug builds
// also warn once per problem). Not counted: sprites the hardware itself skips
// on a scanline that runs out of time (about 1,210 cycles a line: an
// unrotated sprite costs its width, a rotated or enlarged one 2 x its doubled
// width + 10), since only the screen shows those.
SpriteStats sprite_stats(void);

#endif // SERVAL_SPRITES_H
