#ifndef SERVAL_SPRITES_H
#define SERVAL_SPRITES_H

// Sprite assets, sprite groups and drawing. See docs/sprites.md.
//
// Sprite data lives in ROM as constant tables, normally generated by Studio
// Advance's build. Games refer to sprites by ID: an index into the sprite table
// registered with sprite_table_set(). A sprite can be drawn once a group
// containing it has been loaded into VRAM.

#include "serval/platform.h"

// SpriteAsset.size: the sprite's dimensions in pixels (width x height). These
// are the sizes the hardware supports.
#define SPRITE_8x8 1
#define SPRITE_16x16 2
#define SPRITE_32x32 3
#define SPRITE_64x64 4
#define SPRITE_16x8 5
#define SPRITE_32x8 6
#define SPRITE_32x16 7
#define SPRITE_64x32 8
#define SPRITE_8x16 9
#define SPRITE_8x32 10
#define SPRITE_16x32 11
#define SPRITE_32x64 12

// SpriteAsset.flags
#define SPRITE_ASSET_STREAMED (1 << 0)   // not supported yet
#define SPRITE_ASSET_METASPRITE (1 << 1) // not supported yet

// A sprite: its pixels and how to draw them. Fields left out of an
// initializer take sensible defaults; only .size and .tiles are required.
typedef struct {
    const u32* tiles;      // pixel data: 8x8 tiles of 4 bits per pixel, 8 words each,
                           // frame after frame (each frame row by row, tile by tile)
    u8 size;               // SPRITE_16x16 etc. (required)
    u8 frame_count;        // animation frames; 0 means 1
    u8 tiles_per_frame;    // 0: computed from size (the usual case)
    u8 palette_slot;       // which of its group's palettes it uses
    s8 origin_x, origin_y; // drawn position = (x, y) - origin
    u8 flags;              // SPRITE_ASSET_*
    const u8* frame_times; // animation timing, may be NULL
} SpriteAsset;

// SpriteGroup.flags
#define SPRITE_GROUP_RESIDENT 0        // all frames copied to VRAM on load (the default)
#define SPRITE_GROUP_STREAMED (1 << 0) // not supported yet

// Sprites loaded and unloaded together, with the palettes they share.
typedef struct {
    const u16* sprite_ids; // IDs (sprite table indices) of its sprites; NULL means
                           // IDs 0 to sprite_count - 1
    const u16* palettes;   // palette_count banks of 16 colors (color 0 transparent)
    u8 sprite_count;
    u8 palette_count;
    u8 flags; // SPRITE_GROUP_*
} SpriteGroup;

// Most sprite IDs a sprite table may hold.
#define SPRITE_MAX 512

// sprite_draw() flags, combinable with |.
#define SPRITE_FLIP_H (1 << 0)
#define SPRITE_FLIP_V (1 << 1)

// Layering, one of these at most. The screen's layers, front to back, are the
// HUD (background 0, where text.h draws), the foreground (background 1),
// sprites, the playfield (background 2) and the background (background 3); see
// docs/tilemaps.md. By default a sprite sits between the foreground and the
// playfield, so HUD text always stays readable. Among sprites on the same
// layer, the one drawn first is in front.
#define SPRITE_ABOVE_FOREGROUND (3 << 2) // above the foreground, still below the HUD
#define SPRITE_ABOVE_HUD (2 << 2)        // above everything
#define SPRITE_BEHIND_PLAYFIELD (1 << 2) // behind the playfield, above the background

// Registers the game's sprite table: table[id] is the sprite with that ID.
// Unloads all sprite groups.
void sprite_table_set(const SpriteAsset* const* table, u16 count);

// Copies a group's tiles and palettes to VRAM so its sprites can be drawn.
// Returns false, leaving nothing loaded from this group, if sprite VRAM or
// palette banks would run out or the group uses an unsupported feature.
bool sprite_group_load(const SpriteGroup* group);

// Unloads every sprite group, freeing all sprite VRAM and palette banks.
void sprite_groups_reset(void);

// Draws a frame of a sprite this frame. Does nothing if the sprite is not
// loaded, the frame does not exist, it is fully off screen, or all hardware
// sprites are used.
void sprite_draw(u16 sprite_id, u8 frame, int x, int y, u16 flags);

#endif // SERVAL_SPRITES_H
