// asteroids: the arcade classic. Steer a ship, shoot rocks, survive waves.
//
// Demonstrates:
//   - Rotating sprites (sprite_draw_rotated / spr_angle): the ship turns, and
//     rocks spin while sharing a few rotation matrices
//   - Wrap-around physics (physics_set_wrap): everything leaving one edge
//     comes back on the other
//   - Thrust and drag with sine and cosine (fx_sin, fx_cos, fx_mul)
//   - Many short-lived entities (bullets, rocks splitting in two, explosion
//     sparks) created and destroyed every frame, with game components
//   - Collisions with body_overlap, using hitboxes smaller than the sprites
//     (sprite origins center the art on its hitbox)
//   - Sound effects: shots, thrust rumble, explosions, a heartbeat that speeds
//     up as rocks are cleared, and jingles
//   - An attract mode: rocks drift behind the title screen
//
// What to expect when booting the ROM:
//   - Brown, cratered rocks of three sizes drift and spin across a dark blue
//     screen behind "A S T E R O I D S", "PRESS START" and the controls.
//   - After START (a rising chime): a silver arrowhead ship in the center,
//     blinking while it can't be hit, and a wave of large rocks. The top line
//     shows "SCORE", "WAVE" and "SHIPS" (lives).
//   - Left and Right turn the ship; Up thrusts (an orange flame and a low
//     rumble) and the ship drifts on, slowing gently; A fires yellow shots
//     ("pew"), up to 4 at a time, in the direction the ship faces.
//   - Shot rocks burst into sparks with a crunch and split: large into two
//     medium, medium into two small; small ones vanish. 20, 50 and 100 points.
//   - A low two-note heartbeat plays throughout, faster as fewer rocks remain.
//   - Hitting a rock destroys the ship in a bigger burst; a new one appears in
//     the center after a moment, blinking for two seconds. A rising jingle
//     marks an extra ship every 10,000 points.
//   - Clearing all rocks starts the next wave with one more large rock.
//   - With no ships left: "GAME OVER" with a falling tune; START plays again.
//   - START pauses and resumes.
//   (In mGBA's default keyboard mapping: D-pad = arrow keys, A = X,
//   START = Enter.)
//
// Uses only Serval Engine's API; no third-party headers.

#include "serval/serval.h"

// --- Assets ------------------------------------------------------------------

enum {
    SPR_SHIP, // frame 0: coasting; frame 1: thrusting (flame)
    SPR_ROCK_LARGE,
    SPR_ROCK_MEDIUM,
    SPR_ROCK_SMALL,
    SPR_BULLET,
    SPR_SPARK,
    SPRITE_COUNT
};
enum { PAL_SHIP, PAL_ROCK, PAL_BULLET, PAL_SPARK, PALETTE_COUNT };

// Pixel art, 4 bits per pixel, generated by a script from shapes: the ship is
// a shaded arrowhead facing right (rotation turns it), the rocks lumpy
// circles lit from the top left, with craters. Colors: 1 base, 2 highlight,
// 3 shadow, 4 outline, 5 cockpit, 6-7 flame. The ship, for example:
//
//   ...K............
//   ...KKK..........
//   ....KHKK........
//   ....KBBBKKK.....
//   .....KBBBBSKK...
//   .....KBBBCCSSKK.     (nose at the right)
//   .....KBBSCCKK...
//   ....KBBSKKK.....
//   ....KBKK........
//   ...KKK..........
//   ...K............
static const u32 ship_tiles[64] = {
    0x00000000, 0x00000000, 0x00004000, 0x00444000, 0x44240000, 0x11140000, 0x11400000, 0x11400000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000444, 0x00044311, 0x04433551,
    0x11400000, 0x31140000, 0x44140000, 0x00444000, 0x00004000, 0x00000000, 0x00000000, 0x00000000,
    0x00044553, 0x00000444, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00004000, 0x00444000, 0x44240000, 0x11140000, 0x11400670, 0x11406667,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000444, 0x00044311, 0x04433551,
    0x11406667, 0x31140670, 0x44140000, 0x00444000, 0x00004000, 0x00000000, 0x00000000, 0x00000000,
    0x00044553, 0x00000444, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

static const u32 rock_large_tiles[128] = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x40000000, 0x14400000, 0x21240000, 0x12124000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000004, 0x00000442, 0x00004121, 0x00041112,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x44000000, 0x22400000, 0x22400000, 0x22400000, 0x12400000, 0x24000000, 0x14000000,
    0x21212444, 0x12121222, 0x11212122, 0x11121212, 0x11112121, 0x11111212, 0x11111121, 0x11111112,
    0x00411111, 0x04111111, 0x41111111, 0x31111111, 0x13111111, 0x31311111, 0x13331111, 0x31233111,
    0x00000000, 0x00000000, 0x00000000, 0x00000004, 0x00000043, 0x00000041, 0x00000433, 0x00000433,
    0x24000000, 0x14000000, 0x14000000, 0x14000000, 0x14000000, 0x14000000, 0x14000000, 0x40000000,
    0x11111111, 0x11111111, 0x11111111, 0x31111111, 0x13111111, 0x31311111, 0x13131331, 0x31313231,
    0x33131311, 0x33313131, 0x33331313, 0x33333131, 0x33333313, 0x23333331, 0x33333333, 0x33333333,
    0x00000433, 0x00000433, 0x00000433, 0x00000043, 0x00000004, 0x00000004, 0x00000004, 0x00000004,
    0x40000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x33131311, 0x44313134, 0x00444440, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x43333333, 0x43333334, 0x04444440, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

static const u32 rock_medium_tiles[32] = {
    0x00000000, 0x00000000, 0x00000000, 0x44400000, 0x13344400, 0x12322400, 0x11114000, 0x11114000,
    0x00000000, 0x00000000, 0x00004440, 0x00041114, 0x00041133, 0x00043123, 0x00041311, 0x00043131,
    0x11114000, 0x31140000, 0x13140000, 0x31340000, 0x33140000, 0x44400000, 0x00000000, 0x00000000,
    0x00043313, 0x00042331, 0x00042333, 0x00044333, 0x00000433, 0x00000044, 0x00000000, 0x00000000,
};

static const u32 rock_small_tiles[8] = {
    0x00000000, 0x00044400, 0x00043400, 0x04411140, 0x04331140, 0x00433140, 0x00044400, 0x00000000,
};

static const u32 bullet_tiles[8] = {
    0x00000000, 0x00000000, 0x00000000, 0x00022000, 0x00022000, 0x00000000, 0x00000000, 0x00000000,
};

// A spark: a small cross, bright yellow-white in the middle, orange arms.
static const u32 spark_tiles[8] = {
    0x00000000, 0x00000000, 0x00002000, 0x00021200, 0x00002000, 0x00000000, 0x00000000, 0x00000000,
};
static const u16 palettes[PALETTE_COUNT][16] = {
    [PAL_SHIP] = {0, COLOR_RGB(200, 210, 225), COLOR_RGB(255, 255, 255), COLOR_RGB(120, 130, 160),
                  COLOR_RGB(40, 45, 70), COLOR_RGB(80, 220, 255), COLOR_RGB(255, 170, 40),
                  COLOR_RGB(255, 240, 120)},
    [PAL_ROCK] = {0, COLOR_RGB(150, 120, 95), COLOR_RGB(200, 175, 140), COLOR_RGB(95, 72, 58),
                  COLOR_RGB(50, 38, 32), 0, 0, 0},
    [PAL_BULLET] = {0, 0, COLOR_RGB(255, 255, 160), 0, 0, 0, 0, 0},
    [PAL_SPARK] = {0, COLOR_RGB(255, 245, 170), COLOR_RGB(255, 140, 40)},
};

// Sprites are drawn centered on their hitboxes (body_w x body_h, smaller than
// the art so near misses stay misses): origin = (sprite size - hitbox) / 2.
#define SHIP_SIZE 16
#define SHIP_HITBOX 10

static const SpriteAsset sprites[SPRITE_COUNT] = {
    [SPR_SHIP] = {.size = SPRITE_16x16,
                  .frame_count = 2,
                  .tiles = ship_tiles,
                  .palette_slot = PAL_SHIP,
                  .origin_x = 3,
                  .origin_y = 3},
    [SPR_ROCK_LARGE] = {.size = SPRITE_32x32,
                        .tiles = rock_large_tiles,
                        .palette_slot = PAL_ROCK,
                        .origin_x = 4,
                        .origin_y = 4},
    [SPR_ROCK_MEDIUM] = {.size = SPRITE_16x16,
                         .tiles = rock_medium_tiles,
                         .palette_slot = PAL_ROCK,
                         .origin_x = 2,
                         .origin_y = 2},
    [SPR_ROCK_SMALL] = {.size = SPRITE_8x8,
                        .tiles = rock_small_tiles,
                        .palette_slot = PAL_ROCK,
                        .origin_x = 1,
                        .origin_y = 1},
    [SPR_BULLET] = {.size = SPRITE_8x8,
                    .tiles = bullet_tiles,
                    .palette_slot = PAL_BULLET,
                    .origin_x = 3,
                    .origin_y = 3},
    [SPR_SPARK] = {.size = SPRITE_8x8,
                   .tiles = spark_tiles,
                   .palette_slot = PAL_SPARK,
                   .origin_x = 3,
                   .origin_y = 3},
};

static const SpriteAsset* const sprite_table[SPRITE_COUNT] = {
    &sprites[0], &sprites[1], &sprites[2], &sprites[3], &sprites[4], &sprites[5],
};

static const SpriteGroup asteroids_group = {
    .palettes = &palettes[0][0],
    .sprite_count = SPRITE_COUNT,
    .palette_count = PALETTE_COUNT,
};

// --- Sounds --------------------------------------------------------------------

enum {
    SND_START,
    SND_FIRE,
    SND_THRUST,
    SND_EXPLODE_LARGE,
    SND_EXPLODE_MEDIUM,
    SND_EXPLODE_SMALL,
    SND_SHIP_EXPLODE,
    SND_BEAT_LOW,
    SND_BEAT_HIGH,
    SND_EXTRA_SHIP,
    SND_GAME_OVER,
    SND_PAUSE,
    SOUND_COUNT
};

static const u16 start_notes[] = {392, 523, 659, 784};
static const u16 extra_ship_notes[] = {784, 988, 1175, 1568};
static const u16 game_over_notes[] = {392, 330, 262, 196};

// Shots and jingles on square 1, the heartbeat on square 2, rumble and
// explosions on the noise channel.
static const PsgSound sounds[SOUND_COUNT] = {
    [SND_START] = {.channel = PSG_SQUARE1,
                   .duty = PSG_DUTY_25,
                   .frames = 5,
                   .notes = start_notes,
                   .note_count = 4},
    [SND_FIRE] = {.channel = PSG_SQUARE1,
                  .duty = PSG_DUTY_25,
                  .frequency = 1600,
                  .frames = 7,
                  .slide = -1,
                  .slide_size = 2,
                  .fade = -1,
                  .volume = 10},
    [SND_THRUST] = {.channel = PSG_NOISE, .frequency = 2000, .frames = 9, .volume = 6},
    [SND_EXPLODE_LARGE] = {.channel = PSG_NOISE, .frequency = 1500, .fade = -3},
    [SND_EXPLODE_MEDIUM] = {.channel = PSG_NOISE, .frequency = 4000, .fade = -2},
    [SND_EXPLODE_SMALL] = {.channel = PSG_NOISE, .frequency = 9000, .fade = -1},
    [SND_SHIP_EXPLODE] = {.channel = PSG_NOISE, .frequency = 800, .fade = -5},
    [SND_BEAT_LOW] = {.channel = PSG_SQUARE2, .frequency = 98, .frames = 6, .fade = -1},
    [SND_BEAT_HIGH] = {.channel = PSG_SQUARE2, .frequency = 110, .frames = 6, .fade = -1},
    [SND_EXTRA_SHIP] = {.channel = PSG_SQUARE1,
                        .duty = PSG_DUTY_12,
                        .frames = 5,
                        .notes = extra_ship_notes,
                        .note_count = 4},
    [SND_GAME_OVER] = {.channel = PSG_SQUARE1,
                       .duty = PSG_DUTY_25,
                       .frames = 12,
                       .notes = game_over_notes,
                       .note_count = 4},
    [SND_PAUSE] = {.channel = PSG_SQUARE1, .duty = PSG_DUTY_12, .frequency = 784, .frames = 3},
};

static const PsgSound* const sound_table[SOUND_COUNT] = {
    &sounds[0], &sounds[1], &sounds[2], &sounds[3], &sounds[4],  &sounds[5],
    &sounds[6], &sounds[7], &sounds[8], &sounds[9], &sounds[10], &sounds[11],
};

// --- Game state ----------------------------------------------------------------

// Game components: what kind of object an entity is.
#define C_ROCK C_GAME(0)
#define C_BULLET C_GAME(1)
#define C_SPARK C_GAME(2)

#define TURN_SPEED ANGLE_DEG(4) // per frame
#define THRUST (FX_ONE / 12)    // pixels per frame per frame
#define MAX_SPEED FX(3)
#define BULLET_SPEED FX(4)
#define BULLET_LIFE 40 // frames
#define MAX_BULLETS 4
#define FIRE_COOLDOWN 8 // frames between shots
#define SPARK_LIFE 20
#define SPARK_LIMIT_LOW 10      // sparks last 10 to 20 frames
#define RESPAWN_DELAY 90        // frames without a ship after a crash
#define INVULNERABLE_FRAMES 120 // blinking after (re)spawning
#define START_SHIPS 3
#define EXTRA_SHIP_EVERY 10000
#define FIRST_WAVE_ROCKS 4

typedef enum { TITLE, PLAYING, PAUSED, GAME_OVER } State;

// Per-entity game data, beside the engine's component pools.
static u8 life[MAX_ENT];      // C_BULLET, C_SPARK: frames left
static u8 rock_size[MAX_ENT]; // C_ROCK: 0 large, 1 medium, 2 small
static s8 rock_spin[MAX_ENT]; // C_ROCK: +1 or -1

static const u16 rock_sprites[3] = {SPR_ROCK_LARGE, SPR_ROCK_MEDIUM, SPR_ROCK_SMALL};
static const u8 rock_hitbox[3] = {24, 12, 6};
static const u16 rock_points[3] = {20, 50, 100};
static const u16 rock_sounds[3] = {SND_EXPLODE_LARGE, SND_EXPLODE_MEDIUM, SND_EXPLODE_SMALL};

static State state;
static Entity ship = ENTITY_NONE;
static u16 ship_angle;
static int ship_timer; // PLAYING: while > 0, waiting to respawn (no ship) or blinking
static int score, ships, wave, next_extra_ship;
static int fire_cooldown, rumble_timer, explosion_timer;
static int beat_timer, beat_phase;
static u16 spin; // shared rock rotation: every rock uses spin or -spin

// --- Helpers -------------------------------------------------------------------

// Creates an entity with a sprite and a square hitbox centered at (x, y).
static u32 spawn(u32 components, u16 sprite, int hitbox, FIXED x, FIXED y, FIXED vx, FIXED vy) {
    Entity e = entity_create(C_POS | C_VEL | C_SPR | components);
    if (e == ENTITY_NONE)
        return MAX_ENT;
    u32 i = entity_index(e);
    pos_x[i] = x - FX(hitbox) / 2;
    pos_y[i] = y - FX(hitbox) / 2;
    vel_x[i] = vx;
    vel_y[i] = vy;
    spr_id[i] = sprite;
    body_w[i] = body_h[i] = (u8)hitbox;
    return i;
}

static FIXED center_x(u32 i) {
    return pos_x[i] + FX(body_w[i]) / 2;
}

static FIXED center_y(u32 i) {
    return pos_y[i] + FX(body_h[i]) / 2;
}

static void destroy_all(u32 components) {
    ECS_FOR_EACH(i, components) {
        entity_destroy(entity_at(i));
    }
}

// A burst of sparks flying out from (x, y) in random directions.
static void spawn_sparks(FIXED x, FIXED y, int count) {
    for (int k = 0; k < count; k++) {
        u16 dir = (u16)random_u32();
        FIXED speed = FX(1) / 2 + random_range(0, FX(2));
        u32 i = spawn(C_SPARK, SPR_SPARK, 2, x, y, fx_mul(fx_cos(dir), speed),
                      fx_mul(fx_sin(dir), speed));
        if (i < MAX_ENT)
            life[i] = (u8)random_range(SPARK_LIMIT_LOW, SPARK_LIFE);
    }
}

// --- Ship ----------------------------------------------------------------------

static void spawn_ship(void) {
    u32 i = spawn(C_BODY, SPR_SHIP, SHIP_HITBOX, FX(SCREEN_W / 2), FX(SCREEN_H / 2), 0, 0);
    ship = entity_at(i);
    ship_angle = ANGLE_DEG(-90); // facing up
    ship_timer = INVULNERABLE_FRAMES;
}

static void destroy_ship(void) {
    u32 i = entity_index(ship);
    spawn_sparks(center_x(i), center_y(i), 16);
    entity_destroy(ship);
    ship = ENTITY_NONE;
    psg_play(SND_SHIP_EXPLODE);
    explosion_timer = 60;
    ships--;
    ship_timer = RESPAWN_DELAY;
}

static void fire(u32 i) {
    int bullets = 0;
    ECS_FOR_EACH(b, C_BULLET) {
        (void)b;
        bullets++;
    }
    if (bullets >= MAX_BULLETS)
        return;
    FIXED dx = fx_cos(ship_angle), dy = fx_sin(ship_angle);
    // From the nose, at bullet speed plus the ship's own velocity.
    u32 b = spawn(C_BODY | C_BULLET, SPR_BULLET, 2, center_x(i) + dx * 7, center_y(i) + dy * 7,
                  vel_x[i] + fx_mul(dx, BULLET_SPEED), vel_y[i] + fx_mul(dy, BULLET_SPEED));
    if (b < MAX_ENT) {
        life[b] = BULLET_LIFE;
        psg_play(SND_FIRE);
    }
}

static void control_ship(void) {
    if (!entity_alive(ship))
        return;
    u32 i = entity_index(ship);
    if (button_down(BUTTON_LEFT))
        ship_angle = (u16)(ship_angle - TURN_SPEED);
    if (button_down(BUTTON_RIGHT))
        ship_angle = (u16)(ship_angle + TURN_SPEED);
    spr_angle[i] = ship_angle; // the art faces right, which is angle 0

    bool thrusting = button_down(BUTTON_UP);
    spr_frame[i] = thrusting ? 1 : 0;
    if (thrusting) {
        vel_x[i] += fx_mul(fx_cos(ship_angle), THRUST);
        vel_y[i] += fx_mul(fx_sin(ship_angle), THRUST);
        if (--rumble_timer <= 0 && explosion_timer == 0) {
            psg_play(SND_THRUST); // a low rumble, renewed while the button is held
            rumble_timer = 8;
        }
    }
    // Drag: lose 1/64 of the speed each frame, so the ship coasts to a stop.
    vel_x[i] -= vel_x[i] >> 6;
    vel_y[i] -= vel_y[i] >> 6;
    vel_x[i] = int_clamp(vel_x[i], -MAX_SPEED, MAX_SPEED);
    vel_y[i] = int_clamp(vel_y[i], -MAX_SPEED, MAX_SPEED);

    if (fire_cooldown > 0)
        fire_cooldown--;
    if (button_down(BUTTON_A) && fire_cooldown == 0) {
        fire(i);
        fire_cooldown = FIRE_COOLDOWN;
    }

    // Blink while invulnerable: no sprite on alternate 4-frame stretches.
    if (ship_timer > 0)
        ship_timer--;
    bool visible = ship_timer == 0 || (ship_timer / 4) % 2 == 0;
    if (visible)
        ent_mask[i] |= C_SPR;
    else
        ent_mask[i] &= ~C_SPR;
}

// --- Rocks ---------------------------------------------------------------------

// A rock of the given size (0 large to 2 small) at (x, y), drifting in a
// random direction, faster the smaller it is.
static void spawn_rock(int size, FIXED x, FIXED y) {
    u16 dir = (u16)random_u32();
    FIXED speed = FX(1) / 2 + random_range(0, FX(1) / 2) + size * (FX(1) / 2);
    u32 i = spawn(C_BODY | C_ROCK, rock_sprites[size], rock_hitbox[size], x, y,
                  fx_mul(fx_cos(dir), speed), fx_mul(fx_sin(dir), speed));
    if (i < MAX_ENT) {
        rock_size[i] = (u8)size;
        rock_spin[i] = random_range(0, 1) ? 1 : -1;
    }
}

// A new wave: large rocks along the screen edges, away from the center
// where the ship (re)appears.
static void spawn_wave(int count) {
    for (int k = 0; k < count; k++) {
        bool side = random_range(0, 1);
        FIXED x = side ? FX(random_range(0, 1) * (SCREEN_W - 16)) : FX(random_range(0, SCREEN_W));
        FIXED y =
            side ? FX(random_range(16, SCREEN_H)) : FX(16 + random_range(0, 1) * (SCREEN_H - 32));
        spawn_rock(0, x, y);
    }
}

static int rock_count(void) {
    int n = 0;
    ECS_FOR_EACH(i, C_ROCK) {
        (void)i;
        n++;
    }
    return n;
}

static void add_score(int points) {
    score += points;
    if (score >= next_extra_ship) {
        ships++;
        next_extra_ship += EXTRA_SHIP_EVERY;
        psg_play(SND_EXTRA_SHIP);
    }
}

// Splits (or, when small, removes) the rock in slot r, with sparks and sound.
static void break_rock(u32 r) {
    int size = rock_size[r];
    FIXED x = center_x(r), y = center_y(r);
    entity_destroy(entity_at(r));
    spawn_sparks(x, y, 6 - 2 * size);
    psg_play(rock_sounds[size]);
    explosion_timer = 20;
    if (state == PLAYING)
        add_score(rock_points[size]);
    if (size < 2) {
        spawn_rock(size + 1, x, y);
        spawn_rock(size + 1, x, y);
    }
}

// --- Systems -------------------------------------------------------------------

// Spins rocks (sharing two rotation angles) and ages bullets and sparks.
static void update_objects(void) {
    spin = (u16)(spin + ANGLE_DEG(2));
    ECS_FOR_EACH(i, C_ROCK) {
        spr_angle[i] = rock_spin[i] > 0 ? spin : (u16)-spin;
    }
    ECS_FOR_EACH(i, C_BULLET) {
        if (--life[i] == 0)
            entity_destroy(entity_at(i));
    }
    ECS_FOR_EACH(i, C_SPARK) {
        if (--life[i] == 0)
            entity_destroy(entity_at(i));
    }
}

static void check_collisions(void) {
    ECS_FOR_EACH(b, C_BULLET) {
        ECS_FOR_EACH(r, C_ROCK) {
            if (body_overlap(b, r)) {
                entity_destroy(entity_at(b));
                break_rock(r);
                break; // this bullet is gone
            }
        }
    }
    if (entity_alive(ship) && ship_timer == 0) {
        u32 s = entity_index(ship);
        ECS_FOR_EACH(r, C_ROCK) {
            if (body_overlap(s, r)) {
                break_rock(r);
                destroy_ship();
                break;
            }
        }
    }
}

// The heartbeat: two alternating low notes, closer together as rocks thin out.
static void update_heartbeat(void) {
    if (--beat_timer > 0)
        return;
    psg_play(beat_phase ? SND_BEAT_HIGH : SND_BEAT_LOW);
    beat_phase = !beat_phase;
    beat_timer = int_clamp(12 + rock_count() * 2, 14, 48);
}

// --- Screens -------------------------------------------------------------------

static void print_centered(int row, const char* s) {
    int length = 0;
    while (s[length])
        length++;
    text_print_line(0, row, "");
    text_print((TEXT_COLS - length) / 2, row, s);
}

static void draw_hud(void) {
    text_print_line(0, 0, text_format(" SCORE %-6d WAVE %-3d SHIPS %d", score, wave, ships));
}

static void show_title(void) {
    state = TITLE;
    text_clear();
    print_centered(6, "A S T E R O I D S");
    print_centered(10, "PRESS START");
    print_centered(13, "LEFT/RIGHT:TURN  UP:THRUST");
    print_centered(15, "A:FIRE  START:PAUSE");
}

static void start_game(void) {
    destroy_all(C_ROCK);
    destroy_all(C_BULLET);
    destroy_all(C_SPARK);
    score = 0;
    ships = START_SHIPS;
    wave = 1;
    next_extra_ship = EXTRA_SHIP_EVERY;
    beat_timer = 30;
    state = PLAYING;
    text_clear();
    psg_play(SND_START);
    spawn_ship();
    spawn_wave(FIRST_WAVE_ROCKS);
}

static void update_playing(void) {
    control_ship();
    sys_movement();
    sys_physics();
    update_objects();
    check_collisions();
    update_heartbeat();
    if (explosion_timer > 0)
        explosion_timer--;

    if (!entity_alive(ship) && --ship_timer <= 0) {
        if (ships > 0) {
            spawn_ship();
        } else {
            state = GAME_OVER;
            psg_play(SND_GAME_OVER);
            print_centered(9, "GAME OVER");
            print_centered(11, "PRESS START");
        }
    }
    if (rock_count() == 0) {
        wave++;
        spawn_wave(FIRST_WAVE_ROCKS - 1 + wave);
    }
    draw_hud();
}

// --- Main ----------------------------------------------------------------------

int main(void) {
    serval_init();
    sprite_table_set(sprite_table, SPRITE_COUNT);
    sprite_group_load(&asteroids_group);
    psg_table_set(sound_table, SOUND_COUNT);
    screen_set_backdrop(COLOR_RGB(5, 5, 16));
    physics_set_wrap(true, true);

    spawn_wave(FIRST_WAVE_ROCKS); // drifting behind the title
    show_title();

    for (;;) {
        frame_begin();
        bool start = button_pressed(BUTTON_START);
        switch (state) {
        case TITLE:
        case GAME_OVER:
            // Attract mode: the rocks keep drifting and spinning.
            sys_movement();
            sys_physics();
            update_objects();
            if (start) {
                random_seed(random_entropy()); // every game differs
                start_game();
            }
            break;
        case PLAYING:
            if (start) {
                state = PAUSED;
                psg_play(SND_PAUSE);
                print_centered(9, "PAUSED");
            } else {
                update_playing();
            }
            break;
        case PAUSED:
            if (start) {
                state = PLAYING;
                psg_play(SND_PAUSE);
                text_print_line(0, 9, "");
            }
            break;
        }
        sys_render();
        frame_end();
    }
}
