// asteroids: the arcade classic. Steer a ship, shoot rocks, survive waves.
//
// Demonstrates:
//   - The engine's splash screen (serval_splash)
//   - Rotating sprites (sprite_draw_rotated / spr_angle): the ship turns, and
//     rocks spin while sharing a few rotation matrices
//   - Wrap-around physics (physics_set_wrap): the ship, rocks and shots
//     leaving one edge come back on the other (sparks have no body and just
//     fly off)
//   - Thrust and drag with sine and cosine (fx_sin, fx_cos, fx_mul)
//   - Many short-lived entities (bullets, rocks splitting in two, explosion
//     sparks) created and destroyed every frame, with game components
//   - Collisions with body_overlap, using hitboxes smaller than the sprites
//     (sprite origins center the art on its hitbox)
//   - Blinking by toggling SPRITE_HIDDEN in spr_flags
//   - Sound effects: shots, thrust rumble, explosions, a heartbeat that speeds
//     up as rocks are cleared, and jingles; sound priorities keep gunfire from
//     cutting a jingle short and the rumble from cutting an explosion short
//   - An attract mode: rocks drift behind the title screen, which alternates
//     with the high-score table
//   - Save data (save_read, save_write, save_erase): a top-10 table of scores
//     and initials, kept in one save slot as a small versioned struct, with
//     the default table for a first boot or a save that can't be used
//     (scores.c; how a game picks and raises the version is explained there)
//   - A game split into files: main.c runs the game, scores.c the table and
//     the initials entry screen
//
// What to expect when booting the ROM:
//   - First the Serval Engine splash: "made with" and "Serval Engine" fade in
//     on black, a coin-like jingle plays, and they fade out (about 3 seconds;
//     any button skips it once the text is in).
//   - Four large brown, cratered rocks drift and spin across a dark blue
//     screen behind "A S T E R O I D S", "PRESS START" and the controls.
//   - After START (a rising chime): a silver arrowhead ship in the center,
//     blinking while it can't be hit, and a wave of large rocks. The top line
//     shows "SCORE", "WAVE" and "SHIPS" (lives).
//   - Left and Right turn the ship; Up thrusts (an orange flame and a low
//     rumble) and the ship drifts on, slowing gently to a stop; A fires yellow
//     shots ("pew"), up to 4 at a time, in the direction the ship faces.
//   - Shot rocks burst into sparks with a crunch and split: large into two
//     medium, medium into two small; small ones vanish. 20, 50 and 100 points.
//   - A low two-note heartbeat plays throughout, faster as the wave is cleared.
//   - Hitting a rock destroys the ship in a bigger burst (the rock breaks and
//     scores as if shot); a new one appears in the center after a moment,
//     blinking for two seconds. A rising jingle marks an extra ship every
//     10,000 points.
//   - Clearing all rocks starts the next wave with one more large rock (up to
//     14), placed away from the ship.
//   - With no ships left: "GAME OVER" with a falling tune. If the score
//     doesn't make the high-score table, START plays again, and after 10
//     seconds the attract mode comes back.
//   - If it does: after 2 seconds (or START), "NEW HIGH SCORE" with a rising
//     jingle, the score, its place, and three letters "A  A  A" with a caret
//     under the one being changed. UP and DOWN cycle it through A-Z, '.' and
//     space (shown as '_'), with a short blip, repeating while held; A or
//     RIGHT moves to the next letter, B or LEFT back (a lower blip). A on the
//     last letter, or START at any time, confirms with a two-note chime: the
//     table is saved and shown with "> <" blinking around the new entry.
//   - The attract mode alternates every 5 seconds between the title and the
//     "HIGH SCORES" table: places 1 to 10, initials and scores. On a first
//     boot it holds made-up players (SRV 5000 down to MAX 400). The table
//     survives power-off: in mGBA, in the .sav file next to the ROM.
//   - For demos: on the title or the table, hold L and R and press SELECT to
//     erase the saved table. A falling tone plays, and the default table
//     shows with "HIGH SCORES RESET" under it.
//   - START pauses and resumes.
//   (In mGBA's default keyboard mapping: D-pad = arrow keys, A = X, B = Z,
//   L = A, R = S, START = Enter, SELECT = Backspace.)
//
// Uses only Serval Engine's API; no third-party headers.

#include "serval/serval.h"

#include "scores.h"

// --- Assets ------------------------------------------------------------------

enum {
    SPR_SHIP, // frame 0: coasting; frame 1: thrusting (flame)
    SPR_ROCK_LARGE,
    SPR_ROCK_MEDIUM,
    SPR_ROCK_SMALL,
    SPR_BULLET,
    SPR_SPARK,
    SPRITE_COUNT
};
enum { PAL_SHIP, PAL_ROCK, PAL_BULLET, PAL_SPARK, PALETTE_COUNT };

// Pixel art, 4 bits per pixel, generated by a script from shapes: the ship is
// a shaded arrowhead facing right (rotation turns it), the rocks lumpy
// circles lit from the top left, with craters. Colors: 1 base, 2 highlight,
// 3 shadow, 4 outline, 5 cockpit, 6-7 flame. The ship, for example:
//
//   ...K............
//   ...KKK..........
//   ....KHKK........
//   ....KBBBKKK.....
//   .....KBBBBSKK...
//   .....KBBBCCSSKK.     (nose at the right)
//   .....KBBSCCKK...
//   ....KBBSKKK.....
//   ....KBKK........
//   ...KKK..........
//   ...K............
static const u32 ship_tiles[64] = {
    0x00000000, 0x00000000, 0x00004000, 0x00444000, 0x44240000, 0x11140000, 0x11400000, 0x11400000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000444, 0x00044311, 0x04433551,
    0x11400000, 0x31140000, 0x44140000, 0x00444000, 0x00004000, 0x00000000, 0x00000000, 0x00000000,
    0x00044553, 0x00000444, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00004000, 0x00444000, 0x44240000, 0x11140000, 0x11400670, 0x11406667,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000444, 0x00044311, 0x04433551,
    0x11406667, 0x31140670, 0x44140000, 0x00444000, 0x00004000, 0x00000000, 0x00000000, 0x00000000,
    0x00044553, 0x00000444, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

static const u32 rock_large_tiles[128] = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x40000000, 0x14400000, 0x21240000, 0x12124000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000004, 0x00000442, 0x00004121, 0x00041112,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x44000000, 0x22400000, 0x22400000, 0x22400000, 0x12400000, 0x24000000, 0x14000000,
    0x21212444, 0x12121222, 0x11212122, 0x11121212, 0x11112121, 0x11111212, 0x11111121, 0x11111112,
    0x00411111, 0x04111111, 0x41111111, 0x31111111, 0x13111111, 0x31311111, 0x13331111, 0x31233111,
    0x00000000, 0x00000000, 0x00000000, 0x00000004, 0x00000043, 0x00000041, 0x00000433, 0x00000433,
    0x24000000, 0x14000000, 0x14000000, 0x14000000, 0x14000000, 0x14000000, 0x14000000, 0x40000000,
    0x11111111, 0x11111111, 0x11111111, 0x31111111, 0x13111111, 0x31311111, 0x13131331, 0x31313231,
    0x33131311, 0x33313131, 0x33331313, 0x33333131, 0x33333313, 0x23333331, 0x33333333, 0x33333333,
    0x00000433, 0x00000433, 0x00000433, 0x00000043, 0x00000004, 0x00000004, 0x00000004, 0x00000004,
    0x40000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x33131311, 0x44313134, 0x00444440, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x43333333, 0x43333334, 0x04444440, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

static const u32 rock_medium_tiles[32] = {
    0x00000000, 0x00000000, 0x00000000, 0x44400000, 0x13344400, 0x12322400, 0x11114000, 0x11114000,
    0x00000000, 0x00000000, 0x00004440, 0x00041114, 0x00041133, 0x00043123, 0x00041311, 0x00043131,
    0x11114000, 0x31140000, 0x13140000, 0x31340000, 0x33140000, 0x44400000, 0x00000000, 0x00000000,
    0x00043313, 0x00042331, 0x00042333, 0x00044333, 0x00000433, 0x00000044, 0x00000000, 0x00000000,
};

static const u32 rock_small_tiles[8] = {
    0x00000000, 0x00044400, 0x00043400, 0x04411140, 0x04331140, 0x00433140, 0x00044400, 0x00000000,
};

static const u32 bullet_tiles[8] = {
    0x00000000, 0x00000000, 0x00000000, 0x00022000, 0x00022000, 0x00000000, 0x00000000, 0x00000000,
};

// A spark: a small cross, bright yellow-white in the middle, orange arms.
static const u32 spark_tiles[8] = {
    0x00000000, 0x00000000, 0x00002000, 0x00021200, 0x00002000, 0x00000000, 0x00000000, 0x00000000,
};
static const u16 palettes[PALETTE_COUNT][16] = {
    [PAL_SHIP] = {0, COLOR_RGB(200, 210, 225), COLOR_RGB(255, 255, 255), COLOR_RGB(120, 130, 160),
                  COLOR_RGB(40, 45, 70), COLOR_RGB(80, 220, 255), COLOR_RGB(255, 170, 40),
                  COLOR_RGB(255, 240, 120)},
    [PAL_ROCK] = {0, COLOR_RGB(150, 120, 95), COLOR_RGB(200, 175, 140), COLOR_RGB(95, 72, 58),
                  COLOR_RGB(50, 38, 32), 0, 0, 0},
    [PAL_BULLET] = {0, 0, COLOR_RGB(255, 255, 160), 0, 0, 0, 0, 0},
    [PAL_SPARK] = {0, COLOR_RGB(255, 245, 170), COLOR_RGB(255, 140, 40)},
};

// Sprites are drawn centered on their hitboxes (body_w x body_h, smaller than
// the art so near misses stay misses): origin = (sprite size - hitbox) / 2.
#define SHIP_SIZE 16
#define SHIP_HITBOX 10

static const SpriteAsset sprites[SPRITE_COUNT] = {
    [SPR_SHIP] = {.size = SPRITE_16x16,
                  .frame_count = 2,
                  .tiles = ship_tiles,
                  .palette_slot = PAL_SHIP,
                  .origin_x = 3,
                  .origin_y = 3},
    [SPR_ROCK_LARGE] = {.size = SPRITE_32x32,
                        .tiles = rock_large_tiles,
                        .palette_slot = PAL_ROCK,
                        .origin_x = 4,
                        .origin_y = 4},
    [SPR_ROCK_MEDIUM] = {.size = SPRITE_16x16,
                         .tiles = rock_medium_tiles,
                         .palette_slot = PAL_ROCK,
                         .origin_x = 2,
                         .origin_y = 2},
    [SPR_ROCK_SMALL] = {.size = SPRITE_8x8,
                        .tiles = rock_small_tiles,
                        .palette_slot = PAL_ROCK,
                        .origin_x = 1,
                        .origin_y = 1},
    [SPR_BULLET] = {.size = SPRITE_8x8,
                    .tiles = bullet_tiles,
                    .palette_slot = PAL_BULLET,
                    .origin_x = 3,
                    .origin_y = 3},
    [SPR_SPARK] = {.size = SPRITE_8x8,
                   .tiles = spark_tiles,
                   .palette_slot = PAL_SPARK,
                   .origin_x = 3,
                   .origin_y = 3},
};

static const SpriteAsset* const sprite_table[SPRITE_COUNT] = {
    [SPR_SHIP] = &sprites[SPR_SHIP],
    [SPR_ROCK_LARGE] = &sprites[SPR_ROCK_LARGE],
    [SPR_ROCK_MEDIUM] = &sprites[SPR_ROCK_MEDIUM],
    [SPR_ROCK_SMALL] = &sprites[SPR_ROCK_SMALL],
    [SPR_BULLET] = &sprites[SPR_BULLET],
    [SPR_SPARK] = &sprites[SPR_SPARK],
};

static const SpriteGroup asteroids_group = {
    .palettes = &palettes[0][0],
    .sprite_count = SPRITE_COUNT,
    .palette_count = PALETTE_COUNT,
};

// --- Sounds ------------------------------------------------------------------

enum {
    SND_START,
    SND_FIRE,
    SND_THRUST,
    SND_EXPLODE_LARGE,
    SND_EXPLODE_MEDIUM,
    SND_EXPLODE_SMALL,
    SND_SHIP_EXPLODE,
    SND_BEAT_LOW,
    SND_BEAT_HIGH,
    SND_EXTRA_SHIP,
    SND_GAME_OVER,
    SND_PAUSE,
    SND_HIGH_SCORE,
    SND_LETTER,
    SND_NEXT_LETTER,
    SND_CONFIRM,
    SND_RESET,
    SOUND_COUNT
};

static const u16 start_notes[] = {392, 523, 659, 784};
static const u16 extra_ship_notes[] = {784, 988, 1175, 1568};
static const u16 game_over_notes[] = {392, 330, 262, 196};
static const u16 high_score_notes[] = {523, 659, 784, 0, 659, 784, 1047, 1047};
static const u16 confirm_notes[] = {784, 1047};

// Shots, jingles and the pause tick on square 1, the heartbeat on square 2,
// rumble and explosions on the noise channel. A sound can't replace one of
// higher priority on its channel: shots don't cut a jingle short, and the
// thrust rumble (renewed every few frames) doesn't cut an explosion short.
// The initials entry screen's blips use square 2 (the heartbeat is silent by
// then), so typing doesn't cut the high-score jingle short either.
#define JINGLE_PRIORITY 1    // jingles and the pause tick, over shots
#define EXPLOSION_PRIORITY 1 // explosions, over the rumble
static const PsgSound sounds[SOUND_COUNT] = {
    [SND_START] = {.duty = PSG_DUTY_25,
                   .frames = 5,
                   .notes = start_notes,
                   .note_count = 4,
                   .priority = JINGLE_PRIORITY},
    [SND_FIRE] = {.channel = PSG_SQUARE1,
                  .duty = PSG_DUTY_25,
                  .frequency = 1600,
                  .frames = 7,
                  .slide = -1,
                  .slide_size = 2,
                  .fade = -1,
                  .volume = 10},
    [SND_THRUST] = {.channel = PSG_NOISE, .frequency = 2000, .frames = 9, .volume = 6},
    [SND_EXPLODE_LARGE] = {.channel = PSG_NOISE,
                           .frequency = 1500,
                           .fade = -3,
                           .priority = EXPLOSION_PRIORITY},
    [SND_EXPLODE_MEDIUM] = {.channel = PSG_NOISE,
                            .frequency = 4000,
                            .fade = -2,
                            .priority = EXPLOSION_PRIORITY},
    [SND_EXPLODE_SMALL] = {.channel = PSG_NOISE,
                           .frequency = 9000,
                           .fade = -1,
                           .priority = EXPLOSION_PRIORITY},
    [SND_SHIP_EXPLODE] = {.channel = PSG_NOISE,
                          .frequency = 800,
                          .fade = -5,
                          .priority = EXPLOSION_PRIORITY},
    [SND_BEAT_LOW] = {.channel = PSG_SQUARE2, .frequency = 98, .frames = 6, .fade = -1},
    [SND_BEAT_HIGH] = {.channel = PSG_SQUARE2, .frequency = 110, .frames = 6, .fade = -1},
    [SND_EXTRA_SHIP] = {.duty = PSG_DUTY_12,
                        .frames = 5,
                        .notes = extra_ship_notes,
                        .note_count = 4,
                        .priority = JINGLE_PRIORITY},
    [SND_GAME_OVER] = {.duty = PSG_DUTY_25,
                       .frames = 12,
                       .notes = game_over_notes,
                       .note_count = 4,
                       .priority = JINGLE_PRIORITY},
    [SND_PAUSE] = {.duty = PSG_DUTY_12, .frequency = 784, .frames = 3, .priority = JINGLE_PRIORITY},
    [SND_HIGH_SCORE] = {.duty = PSG_DUTY_12,
                        .frames = 6,
                        .notes = high_score_notes,
                        .note_count = 8,
                        .priority = JINGLE_PRIORITY},
    [SND_LETTER] = {.channel = PSG_SQUARE2, .duty = PSG_DUTY_25, .frequency = 1319, .frames = 2},
    [SND_NEXT_LETTER] = {.channel = PSG_SQUARE2,
                         .duty = PSG_DUTY_25,
                         .frequency = 880,
                         .frames = 4},
    [SND_CONFIRM] = {.duty = PSG_DUTY_25,
                     .frames = 5,
                     .notes = confirm_notes,
                     .note_count = 2,
                     .priority = JINGLE_PRIORITY},
    [SND_RESET] =
        {.frequency = 880, .frames = 24, .slide = -2, .slide_size = 3, .priority = JINGLE_PRIORITY},
};

static const PsgSound* const sound_table[SOUND_COUNT] = {
    [SND_START] = &sounds[SND_START],
    [SND_FIRE] = &sounds[SND_FIRE],
    [SND_THRUST] = &sounds[SND_THRUST],
    [SND_EXPLODE_LARGE] = &sounds[SND_EXPLODE_LARGE],
    [SND_EXPLODE_MEDIUM] = &sounds[SND_EXPLODE_MEDIUM],
    [SND_EXPLODE_SMALL] = &sounds[SND_EXPLODE_SMALL],
    [SND_SHIP_EXPLODE] = &sounds[SND_SHIP_EXPLODE],
    [SND_BEAT_LOW] = &sounds[SND_BEAT_LOW],
    [SND_BEAT_HIGH] = &sounds[SND_BEAT_HIGH],
    [SND_EXTRA_SHIP] = &sounds[SND_EXTRA_SHIP],
    [SND_GAME_OVER] = &sounds[SND_GAME_OVER],
    [SND_PAUSE] = &sounds[SND_PAUSE],
    [SND_HIGH_SCORE] = &sounds[SND_HIGH_SCORE],
    [SND_LETTER] = &sounds[SND_LETTER],
    [SND_NEXT_LETTER] = &sounds[SND_NEXT_LETTER],
    [SND_CONFIRM] = &sounds[SND_CONFIRM],
    [SND_RESET] = &sounds[SND_RESET],
};

// --- Game state --------------------------------------------------------------

// Game components: what kind of object an entity is.
#define C_ROCK C_GAME(0)
#define C_BULLET C_GAME(1)
#define C_SPARK C_GAME(2)

#define TURN_SPEED ANGLE_DEG(4) // per frame
#define THRUST (FX_ONE / 12)    // pixels per frame per frame
#define MAX_SPEED FX(3)
#define BULLET_SPEED FX(4)
#define BULLET_LIFE 40 // frames
#define MAX_BULLETS 4
#define FIRE_COOLDOWN 8   // frames between shots
#define SPARK_LIFE_MIN 10 // frames
#define SPARK_LIFE_MAX 20
#define RESPAWN_DELAY 90        // frames without a ship after a crash
#define INVULNERABLE_FRAMES 120 // blinking after (re)spawning
#define START_SHIPS 3
#define EXTRA_SHIP_EVERY 10000
#define FIRST_WAVE_ROCKS 4
#define SPAWN_CLEARANCE 48 // pixels: new rocks appear at least this far from the ship

// Each wave has one more large rock, up to MAX_WAVE_ROCKS, so that everything
// fits in the engine's 128 entities. Worst case: 14 large rocks split into
// 56 small ones; 1 ship and 4 bullets; sparks: 16 from the ship plus 6 per
// broken rock, and while sparks last (20 frames) at most 8 rocks break (the 4
// shots in flight, 3 more fired every 8 frames, 1 hit by the ship), so 64.
// 56 + 1 + 4 + 64 = 125.
#define MAX_WAVE_ROCKS 14

// TITLE is the attract mode, alternating between two pages; NEW_HIGH_SCORE
// is the initials entry screen (scores.c).
typedef enum { TITLE, PLAYING, PAUSED, GAME_OVER, NEW_HIGH_SCORE } State;
typedef enum { PAGE_TITLE, PAGE_SCORES } Page;

#define PAGE_FRAMES 300      // the attract pages alternate every 5 seconds
#define NEW_ENTRY_FRAMES 600 // the table with a new entry stays 10 seconds
#define BLINK_FRAMES 16      // the new entry's markers blink at this pace
#define GAME_OVER_FRAMES 120 // "GAME OVER" before the initials entry screen
#define GAME_OVER_IDLE 600   // without a high score, then the attract mode

// Per-entity game data, beside the engine's component pools.
static u8 life[MAX_ENT];      // C_BULLET, C_SPARK: frames left
static u8 rock_size[MAX_ENT]; // C_ROCK: 0 large, 1 medium, 2 small
static s8 rock_spin[MAX_ENT]; // C_ROCK: +1 or -1

static const u16 rock_sprites[3] = {SPR_ROCK_LARGE, SPR_ROCK_MEDIUM, SPR_ROCK_SMALL};
static const u8 rock_hitbox[3] = {24, 12, 6};
static const u16 rock_points[3] = {20, 50, 100};
static const u16 rock_sounds[3] = {SND_EXPLODE_LARGE, SND_EXPLODE_MEDIUM, SND_EXPLODE_SMALL};

static State state;
static Entity ship = ENTITY_NONE;
static u16 ship_angle;
static int ship_timer; // PLAYING: while > 0, waiting to respawn (no ship) or blinking
static int score, ships, wave, next_extra_ship;
static int fire_cooldown, rumble_timer;
static int beat_timer, beat_phase;
static int wave_shots; // shots it took to clear the wave when it started
static u16 spin;       // shared rock rotation: every rock uses spin or -spin
static Page page;
static int page_timer; // TITLE: frames left on this page; GAME_OVER: frames shown
static int rank;       // the last game's place in the high-score table, or -1
static int highlight;  // the table entry to mark (the newest), or -1

// --- Helpers -----------------------------------------------------------------

// Creates an entity with a sprite and a square hitbox centered at (x, y).
static u32 spawn(u32 components, u16 sprite, int hitbox, FIXED x, FIXED y, FIXED vx, FIXED vy) {
    Entity e = entity_create(C_POS | C_VEL | C_SPR | components);
    if (e == ENTITY_NONE)
        return MAX_ENT;
    u32 i = entity_index(e);
    pos_x[i] = x - FX(hitbox) / 2;
    pos_y[i] = y - FX(hitbox) / 2;
    vel_x[i] = vx;
    vel_y[i] = vy;
    spr_id[i] = sprite;
    body_w[i] = body_h[i] = (u8)hitbox;
    return i;
}

static FIXED center_x(u32 i) {
    return pos_x[i] + FX(body_w[i]) / 2;
}

static FIXED center_y(u32 i) {
    return pos_y[i] + FX(body_h[i]) / 2;
}

static void destroy_all(u32 components) {
    ECS_FOR_EACH(i, components) {
        entity_destroy(entity_at(i));
    }
}

// A burst of sparks flying out from (x, y) in random directions.
static void spawn_sparks(FIXED x, FIXED y, int count) {
    for (int k = 0; k < count; k++) {
        u16 dir = (u16)random_u32();
        FIXED speed = FX_ONE / 2 + random_range(0, FX(2));
        u32 i = spawn(C_SPARK, SPR_SPARK, 2, x, y, fx_mul(fx_cos(dir), speed),
                      fx_mul(fx_sin(dir), speed));
        if (i < MAX_ENT)
            life[i] = (u8)random_range(SPARK_LIFE_MIN, SPARK_LIFE_MAX);
    }
}

// --- Ship --------------------------------------------------------------------

static void spawn_ship(void) {
    u32 i = spawn(C_BODY, SPR_SHIP, SHIP_HITBOX, FX(SCREEN_W / 2), FX(SCREEN_H / 2), 0, 0);
    if (i == MAX_ENT)
        return; // no free entity (see MAX_WAVE_ROCKS): tried again next frame
    ship = entity_at(i);
    ship_angle = ANGLE_DEG(-90); // facing up
    ship_timer = INVULNERABLE_FRAMES;
}

static void destroy_ship(void) {
    u32 i = entity_index(ship);
    spawn_sparks(center_x(i), center_y(i), 16);
    entity_destroy(ship);
    ship = ENTITY_NONE;
    psg_play(SND_SHIP_EXPLODE);
    ships--;
    ship_timer = RESPAWN_DELAY;
}

static void fire(u32 i) {
    int bullets = 0;
    ECS_FOR_EACH(b, C_BULLET) {
        (void)b;
        bullets++;
    }
    if (bullets >= MAX_BULLETS)
        return;
    FIXED dx = fx_cos(ship_angle), dy = fx_sin(ship_angle);
    // From the nose, at bullet speed plus the ship's own velocity.
    u32 b = spawn(C_BODY | C_BULLET, SPR_BULLET, 2, center_x(i) + dx * 7, center_y(i) + dy * 7,
                  vel_x[i] + fx_mul(dx, BULLET_SPEED), vel_y[i] + fx_mul(dy, BULLET_SPEED));
    if (b < MAX_ENT) {
        life[b] = BULLET_LIFE;
        psg_play(SND_FIRE);
    }
}

// Drag: the ship loses 1/64 of its speed each frame (at least 1/256 pixel per
// frame), the same in every direction, so it coasts to a stop.
static FIXED drag(FIXED v) {
    FIXED loss = int_max(int_abs(v) / 64, 1);
    if (int_abs(v) <= loss)
        return 0;
    return v > 0 ? v - loss : v + loss;
}

static void control_ship(void) {
    if (!entity_alive(ship))
        return;
    u32 i = entity_index(ship);
    if (button_down(BUTTON_LEFT))
        ship_angle = (u16)(ship_angle - TURN_SPEED);
    if (button_down(BUTTON_RIGHT))
        ship_angle = (u16)(ship_angle + TURN_SPEED);
    spr_angle[i] = ship_angle; // the art faces right, which is angle 0

    bool thrusting = button_down(BUTTON_UP);
    spr_frame[i] = thrusting ? 1 : 0;
    if (thrusting) {
        vel_x[i] += fx_mul(fx_cos(ship_angle), THRUST);
        vel_y[i] += fx_mul(fx_sin(ship_angle), THRUST);
        if (--rumble_timer <= 0) {
            psg_play(SND_THRUST); // a low rumble, renewed while the button is held
            rumble_timer = 8;
        }
    }
    vel_x[i] = drag(vel_x[i]);
    vel_y[i] = drag(vel_y[i]);
    vel_x[i] = int_clamp(vel_x[i], -MAX_SPEED, MAX_SPEED);
    vel_y[i] = int_clamp(vel_y[i], -MAX_SPEED, MAX_SPEED);

    if (fire_cooldown > 0)
        fire_cooldown--;
    if (button_down(BUTTON_A) && fire_cooldown == 0) {
        fire(i);
        fire_cooldown = FIRE_COOLDOWN;
    }

    // Blink while invulnerable: hidden on alternate 4-frame stretches.
    if (ship_timer > 0)
        ship_timer--;
    bool hidden = ship_timer > 0 && (ship_timer / 4) % 2 == 1;
    spr_flags[i] = hidden ? SPRITE_HIDDEN : 0;
}

// --- Rocks -------------------------------------------------------------------

// A rock of the given size (0 large to 2 small) at (x, y), drifting in a
// random direction, faster the smaller it is.
static void spawn_rock(int size, FIXED x, FIXED y) {
    u16 dir = (u16)random_u32();
    FIXED speed = FX_ONE / 2 + random_range(0, FX_ONE / 2) + size * (FX_ONE / 2);
    u32 i = spawn(C_BODY | C_ROCK, rock_sprites[size], rock_hitbox[size], x, y,
                  fx_mul(fx_cos(dir), speed), fx_mul(fx_sin(dir), speed));
    if (i < MAX_ENT) {
        rock_size[i] = (u8)size;
        rock_spin[i] = random_range(0, 1) ? 1 : -1;
    }
}

// True if (x, y) is too close to the ship for a new rock.
static bool near_ship(FIXED x, FIXED y) {
    if (!entity_alive(ship))
        return false;
    u32 i = entity_index(ship);
    return int_abs(x - center_x(i)) < FX(SPAWN_CLEARANCE) &&
           int_abs(y - center_y(i)) < FX(SPAWN_CLEARANCE);
}

// Shots it takes to clear a rock: a large one splits into two medium, each
// into two small: 1 + 2 + 4.
static const u8 rock_shots[3] = {7, 3, 1};

// A new wave of up to MAX_WAVE_ROCKS large rocks along the screen edges, away
// from the center where the ship (re)appears and from the ship itself.
static void spawn_wave(int count) {
    count = int_min(count, MAX_WAVE_ROCKS);
    for (int k = 0; k < count;) {
        bool side = random_range(0, 1);
        FIXED x = side ? FX(random_range(0, 1) * (SCREEN_W - 16)) : FX(random_range(0, SCREEN_W));
        FIXED y =
            side ? FX(random_range(16, SCREEN_H)) : FX(16 + random_range(0, 1) * (SCREEN_H - 32));
        if (near_ship(x, y))
            continue; // try another spot
        spawn_rock(0, x, y);
        k++;
    }
    wave_shots = count * rock_shots[0];
}

static int rock_count(void) {
    int n = 0;
    ECS_FOR_EACH(i, C_ROCK) {
        (void)i;
        n++;
    }
    return n;
}

// Shots it would take to clear every rock left.
static int shots_left(void) {
    int n = 0;
    ECS_FOR_EACH(i, C_ROCK) {
        n += rock_shots[rock_size[i]];
    }
    return n;
}

static void add_score(int points) {
    score += points;
    if (score >= next_extra_ship) {
        ships++;
        next_extra_ship += EXTRA_SHIP_EVERY;
        psg_play(SND_EXTRA_SHIP);
    }
}

// Splits (or, when small, removes) the rock in slot r, with sparks and sound.
static void break_rock(u32 r) {
    int size = rock_size[r];
    FIXED x = center_x(r), y = center_y(r);
    entity_destroy(entity_at(r));
    spawn_sparks(x, y, 6 - 2 * size);
    psg_play(rock_sounds[size]);
    add_score(rock_points[size]);
    if (size < 2) {
        spawn_rock(size + 1, x, y);
        spawn_rock(size + 1, x, y);
    }
}

// --- Systems -----------------------------------------------------------------

// Spins rocks (sharing two rotation angles) and ages bullets and sparks.
static void update_objects(void) {
    spin = (u16)(spin + ANGLE_DEG(2));
    ECS_FOR_EACH(i, C_ROCK) {
        spr_angle[i] = rock_spin[i] > 0 ? spin : (u16)-spin;
    }
    ECS_FOR_EACH(i, C_BULLET) {
        if (--life[i] == 0)
            entity_destroy(entity_at(i));
    }
    ECS_FOR_EACH(i, C_SPARK) {
        if (--life[i] == 0)
            entity_destroy(entity_at(i));
    }
}

static void check_collisions(void) {
    ECS_FOR_EACH(b, C_BULLET) {
        ECS_FOR_EACH(r, C_ROCK) {
            if (body_overlap(b, r)) {
                entity_destroy(entity_at(b));
                break_rock(r);
                break; // this bullet is gone
            }
        }
    }
    if (entity_alive(ship) && ship_timer == 0) {
        u32 s = entity_index(ship);
        ECS_FOR_EACH(r, C_ROCK) {
            if (body_overlap(s, r)) {
                break_rock(r);
                destroy_ship();
                break;
            }
        }
    }
}

// The heartbeat: two alternating low notes, BEAT_SLOW frames apart when a
// wave starts, closing in on BEAT_FAST as the shots needed to clear it run out.
#define BEAT_SLOW 48
#define BEAT_FAST 14

static void update_heartbeat(void) {
    if (--beat_timer > 0)
        return;
    psg_play(beat_phase ? SND_BEAT_HIGH : SND_BEAT_LOW);
    beat_phase = !beat_phase;
    beat_timer = BEAT_FAST + (BEAT_SLOW - BEAT_FAST) * shots_left() / wave_shots;
}

// --- Screens -----------------------------------------------------------------

static void draw_hud(void) {
    text_print_line(0, 0, text_format(" SCORE %-6d WAVE %-3d SHIPS %d", score, wave, ships));
}

static void start_game(void) {
    random_seed(random_entropy()); // every game differs
    destroy_all(C_ROCK);
    destroy_all(C_BULLET);
    destroy_all(C_SPARK);
    score = 0;
    ships = START_SHIPS;
    wave = 1;
    next_extra_ship = EXTRA_SHIP_EVERY;
    beat_timer = 30;
    state = PLAYING;
    text_clear();
    psg_play(SND_START);
    spawn_ship();
    spawn_wave(FIRST_WAVE_ROCKS);
}

static void update_playing(void) {
    control_ship();
    sys_movement();
    sys_physics();
    update_objects();
    check_collisions();
    update_heartbeat();

    if (!entity_alive(ship) && --ship_timer <= 0) {
        if (ships > 0) {
            spawn_ship();
        } else {
            state = GAME_OVER;
            page_timer = 0;
            rank = scores_rank(score);
            psg_play(SND_GAME_OVER);
            text_print_centered(9, "GAME OVER");
            if (rank < 0)
                text_print_centered(11, "PRESS START");
        }
    }
    if (rock_count() == 0) {
        wave++;
        spawn_wave(FIRST_WAVE_ROCKS - 1 + wave);
    }
    draw_hud();
}

// --- Attract mode, game over and high scores --------------------------------

// Attract mode: the title or the high-score table, shown for some frames.
static void show_page(Page p, int frames) {
    state = TITLE;
    page = p;
    page_timer = frames;
    text_clear();
    if (p == PAGE_TITLE) {
        text_print_centered(6, "A S T E R O I D S");
        text_print_centered(10, "PRESS START");
        text_print_centered(13, "LEFT/RIGHT:TURN  UP:THRUST");
        text_print_centered(15, "A:FIRE  START:PAUSE");
    } else {
        scores_draw(highlight, true);
        text_print_centered(18, "PRESS START");
    }
}

static void update_title(bool start) {
    if (start) {
        start_game();
        return;
    }
    // Hidden, for demos: hold L and R and press SELECT to erase the table.
    if (button_down(BUTTON_L) && button_down(BUTTON_R) && button_pressed(BUTTON_SELECT)) {
        scores_reset();
        highlight = -1;
        show_page(PAGE_SCORES, PAGE_FRAMES);
        text_print_centered(16, "HIGH SCORES RESET");
        psg_play(SND_RESET);
        return;
    }
    if (page == PAGE_SCORES && highlight >= 0 && page_timer % BLINK_FRAMES == 0)
        scores_draw(highlight, page_timer / BLINK_FRAMES % 2 == 0);
    if (--page_timer == 0) {
        highlight = -1; // the newest entry is marked only the first time
        show_page(page == PAGE_TITLE ? PAGE_SCORES : PAGE_TITLE, PAGE_FRAMES);
    }
}

// After "GAME OVER": the initials entry screen if the score made the table
// (START gets there sooner), otherwise START plays again, and after a while
// the attract mode comes back.
static void update_game_over(bool start) {
    page_timer++;
    if (rank >= 0) {
        if (start || page_timer >= GAME_OVER_FRAMES) {
            state = NEW_HIGH_SCORE;
            entry_begin(score);
            psg_play(SND_HIGH_SCORE);
        }
    } else if (start) {
        start_game();
    } else if (page_timer >= GAME_OVER_IDLE) {
        show_page(PAGE_SCORES, PAGE_FRAMES);
    }
}

static void update_new_high_score(void) {
    switch (entry_update()) {
    case ENTRY_LETTER:
        psg_play(SND_LETTER);
        break;
    case ENTRY_MOVE:
        psg_play(SND_NEXT_LETTER);
        break;
    case ENTRY_DONE: // saved: show the table with the new entry marked
        psg_play(SND_CONFIRM);
        highlight = rank;
        show_page(PAGE_SCORES, NEW_ENTRY_FRAMES);
        break;
    case ENTRY_NONE:
        break;
    }
}

// --- Main --------------------------------------------------------------------

int main(void) {
    serval_init();
    serval_splash();
    sprite_table_set(sprite_table, SPRITE_COUNT);
    sprite_group_load(&asteroids_group);
    psg_table_set(sound_table, SOUND_COUNT);
    screen_set_backdrop(COLOR_RGB(5, 5, 16));
    physics_set_wrap(true, true);

    scores_load();
    rank = highlight = -1;
    spawn_wave(FIRST_WAVE_ROCKS); // drifting behind the title
    show_page(PAGE_TITLE, PAGE_FRAMES);

    for (;;) {
        frame_begin();
        bool start = button_pressed(BUTTON_START);
        switch (state) {
        case TITLE:
        case GAME_OVER:
        case NEW_HIGH_SCORE:
            // The rocks keep drifting and spinning behind these screens.
            sys_movement();
            sys_physics();
            update_objects();
            if (state == TITLE)
                update_title(start);
            else if (state == GAME_OVER)
                update_game_over(start);
            else
                update_new_high_score();
            break;
        case PLAYING:
            if (start) {
                state = PAUSED;
                psg_play(SND_PAUSE);
                text_print_centered(9, "PAUSED");
            } else {
                update_playing();
            }
            break;
        case PAUSED:
            if (start) {
                state = PLAYING;
                psg_play(SND_PAUSE);
                text_print_line(0, 9, "");
            }
            break;
        }
        sys_render();
        frame_end();
    }
}
