// Graphics: sprites, their palettes, the background tileset and its map
// layers. The pixel data comes from ASCII pixel art (shown in the comments)
// converted by a script kept outside the repository; edit the art and
// regenerate rather than editing the numbers.

#include "game.h"

// --- Generated by the art script: edit the art there, not the numbers. ---

// Bricks (16x8): plain, silver, cracked silver, gold. Every brick color is
// the same tiles with another palette (B base, H highlight, S shadow, K
// outline, W shine).
// frame 0:
//   HHHHHHHHHHHHHHHK
//   HBBBBBBBBBBBBBSK
//   HBBBBBBBBBBBBBSK
//   HBBBBBBBBBBBBBSK
//   HBBBBBBBBBBBBBSK
//   HBBBBBBBBBBBBBSK
//   HSSSSSSSSSSSSSSK
//   KKKKKKKKKKKKKKKK
// frame 1:
//   HHHHHHHHHHHHHHHK
//   HBBBWWBBBBBBBBSK
//   HBBWWBBBBBBWBBSK
//   HBWWBBBBBBWBBBSK
//   HWWBBBBBBWBBBBSK
//   HBBBBBBBBBBBBBSK
//   HSSSSSSSSSSSSSSK
//   KKKKKKKKKKKKKKKK
// frame 2:
//   HHHHHHHKHHHHHHHK
//   HBBBWWBBKBBBBBSK
//   HBBWWBBKBBBWBBSK
//   HBWWBBBBKKBBBBSK
//   HWWBBBBKBBKBBBSK
//   HBBBBBKBBBBKBBSK
//   HSSSSSKSSSSSKSSK
//   KKKKKKKKKKKKKKKK
// frame 3:
//   HHHHHHHHHHHHHHHK
//   HWSBBBBBBBBBBWSK
//   HSSBBHHBBBBBBSSK
//   HBBBHHBBBBBBBBSK
//   HBBHHBBBBBBBBBSK
//   HWSBBBBBBBBBBWSK
//   HSSSSSSSSSSSSSSK
//   KKKKKKKKKKKKKKKK
static const u32 brick_tiles[64] = {
    0x22222222, 0x11111112, 0x11111112, 0x11111112, 0x11111112, 0x11111112, 0x33333332, 0x44444444,
    0x42222222, 0x43111111, 0x43111111, 0x43111111, 0x43111111, 0x43111111, 0x43333333, 0x44444444,
    0x22222222, 0x11551112, 0x11155112, 0x11115512, 0x11111552, 0x11111112, 0x33333332, 0x44444444,
    0x42222222, 0x43111111, 0x43115111, 0x43111511, 0x43111151, 0x43111111, 0x43333333, 0x44444444,
    0x42222222, 0x11551112, 0x41155112, 0x11115512, 0x41111552, 0x14111112, 0x34333332, 0x44444444,
    0x42222222, 0x43111114, 0x43115111, 0x43111144, 0x43111411, 0x43114111, 0x43343333, 0x44444444,
    0x22222222, 0x11111352, 0x12211332, 0x11221112, 0x11122112, 0x11111352, 0x33333332, 0x44444444,
    0x42222222, 0x43511111, 0x43311111, 0x43111111, 0x43111111, 0x43511111, 0x43333333, 0x44444444,
};

// The ball (6x6 in an 8x8 sprite).
//   .KKKK...
//   KWHHBK..
//   KHHBBK..
//   KHBBSK..
//   KBBSSK..
//   .KKKK...
//   ........
//   ........
static const u32 ball_tiles[8] = {
    0x00044440, 0x00412254, 0x00411224, 0x00431124, 0x00433114, 0x00044440, 0x00000000, 0x00000000,
};

// The paddle's left end (16x8): a serval's spotted coat (X spots).
//   ...KKKKKKKKKKKKK
//   ..KHHHHHHHHHHHHH
//   .KHBBXBBBBBXXBBB
//   KHBXXBBBXBBBBBXB
//   KHBBBBBXXBBBXBBB
//   .KBBXBBBBBBBXXBB
//   ..KSSSSSSSSSSSSS
//   ...KKKKKKKKKKKKK
static const u32 paddle_left_tiles[16] = {
    0x44444000, 0x22222400, 0x11611240, 0x11166124, 0x61111124, 0x11161140, 0x33333400, 0x44444000,
    0x44444444, 0x22222222, 0x11166111, 0x16111116, 0x11161116, 0x11661111, 0x33333333, 0x44444444,
};

// Its middle, added once for the wide paddle.
//   KKKKKKKKKKKKKKKK
//   HHHHHHHHHHHHHHHH
//   BBXBBBBBXXBBBBXB
//   BXXBBXBBBBBXBBBB
//   BBBBBXXBBBBXXBBX
//   BXBBBBBBXBBBBBBB
//   SSSSSSSSSSSSSSSS
//   KKKKKKKKKKKKKKKK
static const u32 paddle_middle_tiles[16] = {
    0x44444444, 0x22222222, 0x11111611, 0x11611661, 0x16611111, 0x11111161, 0x33333333, 0x44444444,
    0x44444444, 0x22222222, 0x16111166, 0x11116111, 0x61166111, 0x11111116, 0x33333333, 0x44444444,
};

// Its right end.
//   KKKKKKKKKKKKK...
//   HHHHHHHHHHHHSK..
//   BXBBBBXXBBBBBSK.
//   BBBXBBBBBXXBBBSK
//   XBBXXBBBBBBXBBSK
//   BBBBBBXBBBBBBSK.
//   SSSSSSSSSSSSSK..
//   KKKKKKKKKKKKK...
static const u32 paddle_right_tiles[16] = {
    0x44444444, 0x22222222, 0x66111161, 0x11116111, 0x11166116, 0x16111111, 0x33333333, 0x44444444,
    0x00044444, 0x00432222, 0x04311111, 0x43111661, 0x43116111, 0x04311111, 0x00433333, 0x00044444,
};

// Power-up capsule 'wide' (16x8): five frames, a glint (Y) sweeping across.
// frame 0:
//   .KKKKKKKKKKKKKK.
//   KHHHHWHHHWHHHHSK
//   KBBBBWBBBWBBBBSK
//   KBBBBWBWBWBBBBSK
//   KBBBBWWBWWBBBBSK
//   KBBBBWBBBWBBBBSK
//   KSSSSSSSSSSSSSSK
//   .KKKKKKKKKKKKKK.
// frame 2:
//   .KKKKKKKKKKKKKK.
//   KHHHHWYHHWHHHHSK
//   KBBBYWBBBWBBBBSK
//   KBBBYWBWBWBBBBSK
//   KBBYYWWBWWBBBBSK
//   KBBYYWBBBWBBBBSK
//   KSYYSSSSSSSSSSSK
//   .KKKKKKKKKKKKKK.
static const u32 capsule_wide_tiles[80] = {
    0x44444440, 0x22522224, 0x11511114, 0x51511114, 0x15511114, 0x11511114, 0x33333334, 0x44444440,
    0x04444444, 0x43222252, 0x43111151, 0x43111151, 0x43111155, 0x43111151, 0x43333333, 0x04444444,
    0x44444440, 0x22527724, 0x11511774, 0x51511774, 0x15511174, 0x11511174, 0x33333334, 0x44444440,
    0x04444444, 0x43222252, 0x43111151, 0x43111151, 0x43111155, 0x43111151, 0x43333333, 0x04444444,
    0x44444440, 0x27522224, 0x11571114, 0x51571114, 0x15577114, 0x11577114, 0x33337734, 0x44444440,
    0x04444444, 0x43222252, 0x43111151, 0x43111151, 0x43111155, 0x43111151, 0x43333333, 0x04444444,
    0x44444440, 0x22522224, 0x11511114, 0x51511114, 0x15511114, 0x11511114, 0x73333334, 0x44444440,
    0x04444444, 0x43227752, 0x43111751, 0x43111751, 0x43111155, 0x43111157, 0x43333337, 0x04444444,
    0x44444440, 0x22522224, 0x11511114, 0x51511114, 0x15511114, 0x11511114, 0x33333334, 0x44444440,
    0x04444444, 0x47722252, 0x43771151, 0x43771151, 0x43177155, 0x43177151, 0x43337733, 0x04444444,
};

// Power-up capsule 'multi' (16x8): five frames, a glint (Y) sweeping across.
// frame 0:
//   .KKKKKKKKKKKKKK.
//   KHHHHWHHHWHHHHSK
//   KBBBBWWBWWBBBBSK
//   KBBBBWBWBWBBBBSK
//   KBBBBWBBBWBBBBSK
//   KBBBBWBBBWBBBBSK
//   KSSSSSSSSSSSSSSK
//   .KKKKKKKKKKKKKK.
static const u32 capsule_multi_tiles[80] = {
    0x44444440, 0x22522224, 0x15511114, 0x51511114, 0x11511114, 0x11511114, 0x33333334, 0x44444440,
    0x04444444, 0x43222252, 0x43111155, 0x43111151, 0x43111151, 0x43111151, 0x43333333, 0x04444444,
    0x44444440, 0x22527724, 0x15511774, 0x51511774, 0x11511174, 0x11511174, 0x33333334, 0x44444440,
    0x04444444, 0x43222252, 0x43111155, 0x43111151, 0x43111151, 0x43111151, 0x43333333, 0x04444444,
    0x44444440, 0x27522224, 0x15571114, 0x51571114, 0x11577114, 0x11577114, 0x33337734, 0x44444440,
    0x04444444, 0x43222252, 0x43111155, 0x43111151, 0x43111151, 0x43111151, 0x43333333, 0x04444444,
    0x44444440, 0x22522224, 0x15511114, 0x51511114, 0x11511114, 0x11511114, 0x73333334, 0x44444440,
    0x04444444, 0x43227752, 0x43111755, 0x43111751, 0x43111157, 0x43111157, 0x43333337, 0x04444444,
    0x44444440, 0x22522224, 0x15511114, 0x51511114, 0x11511114, 0x11511114, 0x33333334, 0x44444440,
    0x04444444, 0x47722252, 0x43771155, 0x43771151, 0x43177151, 0x43177151, 0x43337733, 0x04444444,
};

// Power-up capsule 'slow' (16x8): five frames, a glint (Y) sweeping across.
// frame 0:
//   .KKKKKKKKKKKKKK.
//   KHHHHHWWWWHHHHSK
//   KBBBBWBBBBBBBBSK
//   KBBBBBWWWBBBBBSK
//   KBBBBBBBBWBBBBSK
//   KBBBBWWWWBBBBBSK
//   KSSSSSSSSSSSSSSK
//   .KKKKKKKKKKKKKK.
static const u32 capsule_slow_tiles[80] = {
    0x44444440, 0x55222224, 0x11511114, 0x55111114, 0x11111114, 0x55511114, 0x33333334, 0x44444440,
    0x04444444, 0x43222255, 0x43111111, 0x43111115, 0x43111151, 0x43111115, 0x43333333, 0x04444444,
    0x44444440, 0x55227724, 0x11511774, 0x55111774, 0x11111174, 0x55511174, 0x33333334, 0x44444440,
    0x04444444, 0x43222255, 0x43111111, 0x43111115, 0x43111151, 0x43111115, 0x43333333, 0x04444444,
    0x44444440, 0x55722224, 0x11571114, 0x55771114, 0x11177114, 0x55577114, 0x33337734, 0x44444440,
    0x04444444, 0x43222255, 0x43111111, 0x43111115, 0x43111151, 0x43111115, 0x43333333, 0x04444444,
    0x44444440, 0x55222224, 0x11511114, 0x55111114, 0x11111114, 0x55511114, 0x73333334, 0x44444440,
    0x04444444, 0x43227755, 0x43111771, 0x43111775, 0x43111157, 0x43111175, 0x43333337, 0x04444444,
    0x44444440, 0x55222224, 0x11511114, 0x55111114, 0x11111114, 0x55511114, 0x33333334, 0x44444440,
    0x04444444, 0x47722255, 0x43771111, 0x43771115, 0x43177151, 0x43177115, 0x43337733, 0x04444444,
};

// Power-up capsule 'catch' (16x8): five frames, a glint (Y) sweeping across.
// frame 0:
//   .KKKKKKKKKKKKKK.
//   KHHHHHWWWWHHHHSK
//   KBBBBWBBBBBBBBSK
//   KBBBBWBBBBBBBBSK
//   KBBBBWBBBBBBBBSK
//   KBBBBBWWWWBBBBSK
//   KSSSSSSSSSSSSSSK
//   .KKKKKKKKKKKKKK.
static const u32 capsule_catch_tiles[80] = {
    0x44444440, 0x55222224, 0x11511114, 0x11511114, 0x11511114, 0x55111114, 0x33333334, 0x44444440,
    0x04444444, 0x43222255, 0x43111111, 0x43111111, 0x43111111, 0x43111155, 0x43333333, 0x04444444,
    0x44444440, 0x55227724, 0x11511774, 0x11511774, 0x11511174, 0x55111174, 0x33333334, 0x44444440,
    0x04444444, 0x43222255, 0x43111111, 0x43111111, 0x43111111, 0x43111155, 0x43333333, 0x04444444,
    0x44444440, 0x55722224, 0x11571114, 0x11571114, 0x11577114, 0x55177114, 0x33337734, 0x44444440,
    0x04444444, 0x43222255, 0x43111111, 0x43111111, 0x43111111, 0x43111155, 0x43333333, 0x04444444,
    0x44444440, 0x55222224, 0x11511114, 0x11511114, 0x11511114, 0x55111114, 0x73333334, 0x44444440,
    0x04444444, 0x43227755, 0x43111771, 0x43111771, 0x43111177, 0x43111155, 0x43333337, 0x04444444,
    0x44444440, 0x55222224, 0x11511114, 0x11511114, 0x11511114, 0x55111114, 0x33333334, 0x44444440,
    0x04444444, 0x47722255, 0x43771111, 0x43771111, 0x43177111, 0x43177155, 0x43337733, 0x04444444,
};

// Power-up capsule 'life' (16x8): five frames, a glint (Y) sweeping across.
// frame 0:
//   .KKKKKKKKKKKKKK.
//   KHHHHHWHWHHHHHSK
//   KBBBBWWWWWBBBBSK
//   KBBBBWWWWWBBBBSK
//   KBBBBBWWWBBBBBSK
//   KBBBBBBWBBBBBBSK
//   KSSSSSSSSSSSSSSK
//   .KKKKKKKKKKKKKK.
static const u32 capsule_life_tiles[80] = {
    0x44444440, 0x25222224, 0x55511114, 0x55511114, 0x55111114, 0x51111114, 0x33333334, 0x44444440,
    0x04444444, 0x43222225, 0x43111155, 0x43111155, 0x43111115, 0x43111111, 0x43333333, 0x04444444,
    0x44444440, 0x25227724, 0x55511774, 0x55511774, 0x55111174, 0x51111174, 0x33333334, 0x44444440,
    0x04444444, 0x43222225, 0x43111155, 0x43111155, 0x43111115, 0x43111111, 0x43333333, 0x04444444,
    0x44444440, 0x25722224, 0x55571114, 0x55571114, 0x55177114, 0x51177114, 0x33337734, 0x44444440,
    0x04444444, 0x43222225, 0x43111155, 0x43111155, 0x43111115, 0x43111111, 0x43333333, 0x04444444,
    0x44444440, 0x25222224, 0x55511114, 0x55511114, 0x55111114, 0x51111114, 0x73333334, 0x44444440,
    0x04444444, 0x43227725, 0x43111755, 0x43111755, 0x43111175, 0x43111177, 0x43333337, 0x04444444,
    0x44444440, 0x25222224, 0x55511114, 0x55511114, 0x55111114, 0x51111114, 0x33333334, 0x44444440,
    0x04444444, 0x47722225, 0x43771155, 0x43771155, 0x43177115, 0x43177111, 0x43337733, 0x04444444,
};

// A broken brick's dust (16x8): three frames, then blank.
// frame 0:
//   ................
//   ..HH....W...HH..
//   .HBBH..WW..HBBH.
//   ..HBS.......HBS.
//   ....WW..HH......
//   .HH....HBBH..W..
//   HBBH....HS..WW..
//   .SS.............
// frame 1:
//   .H...........H..
//   HB.....W.......H
//   ........W..S....
//   ...B..........B.
//   .S.......H......
//   ......B......S..
//   ..W..........W..
//   S......S.......B
// frame 2:
//   S..............S
//   ................
//   .......S........
//   ................
//   ................
//   ...S.......S....
//   ................
//   S..............S
static const u32 burst_tiles[64] = {
    0x00000000, 0x00002200, 0x50021120, 0x00031200, 0x00550000, 0x20000220, 0x00002112, 0x00000330,
    0x00000000, 0x00220005, 0x02112005, 0x03120000, 0x00000022, 0x00500211, 0x00550032, 0x00000000,
    0x00000020, 0x50000012, 0x00000000, 0x00001000, 0x00000030, 0x01000000, 0x00000500, 0x30000003,
    0x00200000, 0x20000000, 0x00003005, 0x01000000, 0x00000020, 0x00300000, 0x00500000, 0x10000000,
    0x00000003, 0x00000000, 0x30000000, 0x00000000, 0x00000000, 0x00003000, 0x00000000, 0x00000003,
    0x30000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00003000, 0x00000000, 0x30000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

// A paw print (8x8): one on the HUD for each life left.
//   .K.K.K..
//   KBKBKBK.
//   .K.K.K..
//   ..KKK...
//   .KBBBK..
//   KBBBBBK.
//   .KKKKK..
//   ........
static const u32 paw_tiles[8] = {
    0x00404040, 0x04141414, 0x00404040, 0x00044400, 0x00411140, 0x04111114, 0x00444440, 0x00000000,
};

// Background tiles. The spot motif (16x16, four tiles), drawn in each
// level's pattern bank (B base, S rim, H spot):
//   BBBBBBBBBBBBBBBB
//   BBBSSSBBBBBBBBBB
//   BBSHHHSBBBBBBBBB
//   BBSHHHSBBBBBSSBB
//   BBBSSSBBBBBSHHSB
//   BBBBBBBBBBBSHHSB
//   BBBBBBBBBBBBSSBB
//   BBBBBBBBBBBBBBBB
//   BBBBBBSSBBBBBBBB
//   BBBBBSHHSBBBBBBB
//   BSSBBSHHSBBBBBBB
//   SHHSBBSSBBBBSSSB
//   SHHSBBBBBBBSHHHS
//   BSSBBBBBBBBSHHHS
//   BBBBBBBBBBBBSSSB
//   BBBBBBBBBBBBBBBB
// The frame (bank BANK_FRAME): a pipe with collars every 16 pixels, and
// the HUD band. Side wall, its collar, the top wall's collar, the corner:
//   KHPPPPSK  KHPPPPSK  KKKKHSKK  KKKKKKKK
//   KHPPPPSK  KHPPPPSK  HHKHPSKH  KHHHHHHH
//   KHPPPPSK  KKKKKKKK  PPKHOSKP  KHPPPPPP
//   KHPPPPSK  HHHHHHHK  PPKHPSKP  KHPOOPPP
//   KHPPPPSK  HPOPPOSK  PPKHPSKP  KHPOOPPP
//   KHPPPPSK  SSSSSSSK  PPKHOSKP  KHPPPPPP
//   KHPPPPSK  KKKKKKKK  SSKHPSKS  KHPPPPSS
//   KHPPPPSK  KHPPPPSK  KKKKSSKK  KHPPPPSK
#define TILE_BLANK 0
#define TILE_SPOTS 1
#define TILE_BAND 5
#define TILE_WALL_V 6
#define TILE_WALL_V_JOINT 7
#define TILE_WALL_H 8
#define TILE_WALL_H_JOINT 9
#define TILE_CORNER 10
#define BG_TILE_COUNT 11
static const u32 bg_tiles[88] = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x11111111, 0x11333111, 0x13222311, 0x13222311, 0x11333111, 0x11111111, 0x11111111, 0x11111111,
    0x11111111, 0x11111111, 0x11111111, 0x11331111, 0x13223111, 0x13223111, 0x11331111, 0x11111111,
    0x33111111, 0x22311111, 0x22311331, 0x33113223, 0x11113223, 0x11111331, 0x11111111, 0x11111111,
    0x11111111, 0x11111113, 0x11111113, 0x13331111, 0x32223111, 0x32223111, 0x13331111, 0x11111111,
    0x11111111, 0x11111111, 0x11111111, 0x11111111, 0x11111111, 0x11111111, 0x11111111, 0x11111111,
    0x54333325, 0x54333325, 0x54333325, 0x54333325, 0x54333325, 0x54333325, 0x54333325, 0x54333325,
    0x54333325, 0x54333325, 0x55555555, 0x52222222, 0x54633632, 0x54444444, 0x55555555, 0x54333325,
    0x55555555, 0x22222222, 0x33333333, 0x33333333, 0x33333333, 0x33333333, 0x44444444, 0x55555555,
    0x55425555, 0x25432522, 0x35462533, 0x35432533, 0x35432533, 0x35462533, 0x45432544, 0x55445555,
    0x55555555, 0x22222225, 0x33333325, 0x33366325, 0x33366325, 0x33333325, 0x44333325, 0x54333325,
};

// --- Sprites -----------------------------------------------------------------

// Sprite palettes (PAL_*, game.h). Every palette uses the same color numbers:
// 1 base, 2 highlight, 3 shadow, 4 outline, 5 white, 6 spots (the paddle's),
// 7 glint (the capsules'). The brick colors double as the capsules' colors.

#define BRICK_PALETTE(base, light, dark, outline)                                                  \
    {0, base, light, dark, outline, COLOR_RGB(255, 255, 255), outline, COLOR_RGB(255, 250, 220)}

static const u16 palettes[PALETTE_COUNT][16] = {
    [PAL_RED] = BRICK_PALETTE(COLOR_RGB(220, 50, 50), COLOR_RGB(255, 140, 120),
                              COLOR_RGB(140, 20, 30), COLOR_RGB(60, 10, 20)),
    [PAL_ORANGE] = BRICK_PALETTE(COLOR_RGB(240, 130, 30), COLOR_RGB(255, 200, 120),
                                 COLOR_RGB(170, 70, 10), COLOR_RGB(70, 30, 5)),
    [PAL_YELLOW] = BRICK_PALETTE(COLOR_RGB(235, 205, 40), COLOR_RGB(255, 250, 160),
                                 COLOR_RGB(165, 125, 10), COLOR_RGB(80, 60, 5)),
    [PAL_GREEN] = BRICK_PALETTE(COLOR_RGB(60, 190, 70), COLOR_RGB(160, 240, 140),
                                COLOR_RGB(20, 120, 40), COLOR_RGB(10, 50, 20)),
    [PAL_BLUE] = BRICK_PALETTE(COLOR_RGB(50, 120, 230), COLOR_RGB(140, 200, 255),
                               COLOR_RGB(20, 60, 160), COLOR_RGB(10, 25, 70)),
    [PAL_PURPLE] = BRICK_PALETTE(COLOR_RGB(160, 70, 210), COLOR_RGB(220, 160, 255),
                                 COLOR_RGB(100, 30, 150), COLOR_RGB(45, 10, 70)),
    [PAL_SILVER] = BRICK_PALETTE(COLOR_RGB(170, 180, 195), COLOR_RGB(235, 240, 250),
                                 COLOR_RGB(110, 115, 135), COLOR_RGB(50, 52, 65)),
    [PAL_GOLD] = BRICK_PALETTE(COLOR_RGB(220, 170, 40), COLOR_RGB(255, 235, 140),
                               COLOR_RGB(150, 100, 20), COLOR_RGB(70, 45, 5)),
    [PAL_FLASH] = BRICK_PALETTE(COLOR_RGB(255, 255, 255), COLOR_RGB(255, 255, 255),
                                COLOR_RGB(220, 225, 235), COLOR_RGB(150, 155, 170)),
    [PAL_BALL] = BRICK_PALETTE(COLOR_RGB(225, 225, 230), COLOR_RGB(255, 255, 255),
                               COLOR_RGB(150, 150, 170), COLOR_RGB(50, 50, 70)),
    [PAL_PADDLE] = {0, COLOR_RGB(235, 150, 40), COLOR_RGB(255, 215, 130), COLOR_RGB(170, 90, 20),
                    COLOR_RGB(60, 30, 10), COLOR_RGB(255, 255, 255), COLOR_RGB(70, 35, 10)},
    // Catching: the same coat with a cyan glow around it.
    [PAL_CATCH] = {0, COLOR_RGB(245, 175, 80), COLOR_RGB(180, 255, 240), COLOR_RGB(170, 90, 20),
                   COLOR_RGB(20, 150, 150), COLOR_RGB(255, 255, 255), COLOR_RGB(70, 35, 10)},
};

// The capsules' glint: frame 0 (none) holds for a while, then the glint
// crosses in four quick steps.
static const u8 capsule_times[5] = {40, 3, 3, 3, 3};
#define CAPSULE_SPRITE(tiles_, palette)                                                            \
    {.size = SPRITE_16x8,                                                                          \
     .tiles = (tiles_),                                                                            \
     .frame_count = 5,                                                                             \
     .frame_times = capsule_times,                                                                 \
     .palette_slot = (palette)}

static const u8 burst_times[4] = {5, 5, 5, 1};

static const SpriteAsset sprites[SPRITE_COUNT] = {
    // One brick for every color: drawn with SPRITE_PALETTE(PAL_ORANGE) and
    // so on (red is its own palette), and PAL_FLASH for a hit.
    [SPR_BRICK] = {.size = SPRITE_16x8,
                   .tiles = brick_tiles,
                   .frame_count = 4,
                   .palette_slot = PAL_RED},
    [SPR_BALL] = {.size = SPRITE_8x8, .tiles = ball_tiles, .palette_slot = PAL_BALL},
    [SPR_PADDLE_LEFT] = {.size = SPRITE_16x8,
                         .tiles = paddle_left_tiles,
                         .palette_slot = PAL_PADDLE},
    [SPR_PADDLE_MIDDLE] = {.size = SPRITE_16x8,
                           .tiles = paddle_middle_tiles,
                           .palette_slot = PAL_PADDLE},
    [SPR_PADDLE_RIGHT] = {.size = SPRITE_16x8,
                          .tiles = paddle_right_tiles,
                          .palette_slot = PAL_PADDLE},
    [SPR_CAPSULE_WIDE] = CAPSULE_SPRITE(capsule_wide_tiles, PAL_BLUE),
    [SPR_CAPSULE_MULTI] = CAPSULE_SPRITE(capsule_multi_tiles, PAL_PURPLE),
    [SPR_CAPSULE_SLOW] = CAPSULE_SPRITE(capsule_slow_tiles, PAL_ORANGE),
    [SPR_CAPSULE_CATCH] = CAPSULE_SPRITE(capsule_catch_tiles, PAL_GREEN),
    [SPR_CAPSULE_LIFE] = CAPSULE_SPRITE(capsule_life_tiles, PAL_RED),
    [SPR_BURST] = {.size = SPRITE_16x8,
                   .tiles = burst_tiles,
                   .frame_count = 4,
                   .frame_times = burst_times,
                   .flags = SPRITE_ASSET_ANIM_ONCE,
                   .palette_slot = PAL_BALL},
    [SPR_PAW] = {.size = SPRITE_8x8, .tiles = paw_tiles, .palette_slot = PAL_PADDLE},
};

const SpriteAsset* const sprite_table[SPRITE_COUNT] = {
    [SPR_BRICK] = &sprites[SPR_BRICK],
    [SPR_BALL] = &sprites[SPR_BALL],
    [SPR_PADDLE_LEFT] = &sprites[SPR_PADDLE_LEFT],
    [SPR_PADDLE_MIDDLE] = &sprites[SPR_PADDLE_MIDDLE],
    [SPR_PADDLE_RIGHT] = &sprites[SPR_PADDLE_RIGHT],
    [SPR_CAPSULE_WIDE] = &sprites[SPR_CAPSULE_WIDE],
    [SPR_CAPSULE_MULTI] = &sprites[SPR_CAPSULE_MULTI],
    [SPR_CAPSULE_SLOW] = &sprites[SPR_CAPSULE_SLOW],
    [SPR_CAPSULE_CATCH] = &sprites[SPR_CAPSULE_CATCH],
    [SPR_CAPSULE_LIFE] = &sprites[SPR_CAPSULE_LIFE],
    [SPR_BURST] = &sprites[SPR_BURST],
    [SPR_PAW] = &sprites[SPR_PAW],
};

const SpriteGroup sprite_group = {
    .palettes = &palettes[0][0],
    .sprite_count = SPRITE_COUNT,
    .palette_count = PALETTE_COUNT,
};

// --- Backgrounds -------------------------------------------------------------

// Background palette banks: one per level style for the spot pattern (1 base,
// 2 spot, 3 rim: dark and close together, so the ball stands out), and the
// frame's (1 HUD band, 2 highlight, 3 pipe, 4 shadow, 5 outline, 6 bolts).
enum { BANK_NAVY, BANK_TEAL, BANK_PLUM, BANK_RUST, BANK_FRAME, BANK_COUNT };

static const u16 bg_palettes[BANK_COUNT][16] = {
    [BANK_NAVY] = {0, COLOR_RGB(20, 28, 60), COLOR_RGB(36, 50, 98), COLOR_RGB(28, 38, 78)},
    [BANK_TEAL] = {0, COLOR_RGB(12, 46, 52), COLOR_RGB(22, 78, 84), COLOR_RGB(18, 62, 68)},
    [BANK_PLUM] = {0, COLOR_RGB(44, 20, 56), COLOR_RGB(74, 36, 90), COLOR_RGB(60, 28, 74)},
    [BANK_RUST] = {0, COLOR_RGB(54, 30, 20), COLOR_RGB(90, 52, 32), COLOR_RGB(72, 42, 26)},
    [BANK_FRAME] = {0, COLOR_RGB(12, 12, 20), COLOR_RGB(220, 225, 240), COLOR_RGB(140, 150, 175),
                    COLOR_RGB(80, 86, 110), COLOR_RGB(30, 32, 45), COLOR_RGB(255, 210, 90)},
};

const Tileset tileset = {
    .tiles = bg_tiles,
    .tile_count = BG_TILE_COUNT,
    .palettes = &bg_palettes[0][0],
    .palette_count = BANK_COUNT,
};

enum {
    MT_EMPTY,
    MT_CORNER_LEFT, // the top row: the HUD band over the top pipe
    MT_TOP,
    MT_CORNER_RIGHT,
    MT_WALL_LEFT, // the side pipes, on the outer half of the field's columns
    MT_WALL_RIGHT,
    MT_SPOTS, // the pattern, once per level style (bank)
    MT_COUNT = MT_SPOTS + LEVEL_STYLES
};

#define SE_FRAME(tile, flips) MAP_SE(tile, BANK_FRAME, flips)
#define SPOTS(bank)                                                                                \
    {{MAP_SE(TILE_SPOTS, bank, 0), MAP_SE(TILE_SPOTS + 1, bank, 0),                                \
      MAP_SE(TILE_SPOTS + 2, bank, 0), MAP_SE(TILE_SPOTS + 3, bank, 0)},                           \
     MAP_EMPTY}

// Nothing collides with the map in this game (the balls bounce off
// physics_set_bounds), so every metatile is MAP_EMPTY.
static const Metatile metatiles[MT_COUNT] = {
    [MT_EMPTY] = {{0, 0, 0, 0}, MAP_EMPTY},
    [MT_CORNER_LEFT] = {{SE_FRAME(TILE_BAND, 0), SE_FRAME(TILE_BAND, 0), SE_FRAME(TILE_CORNER, 0),
                         SE_FRAME(TILE_WALL_H, 0)},
                        MAP_EMPTY},
    [MT_TOP] = {{SE_FRAME(TILE_BAND, 0), SE_FRAME(TILE_BAND, 0), SE_FRAME(TILE_WALL_H_JOINT, 0),
                 SE_FRAME(TILE_WALL_H, 0)},
                MAP_EMPTY},
    [MT_CORNER_RIGHT] = {{SE_FRAME(TILE_BAND, 0), SE_FRAME(TILE_BAND, 0),
                          SE_FRAME(TILE_WALL_H_JOINT, 0), SE_FRAME(TILE_CORNER, MAP_SE_FLIP_H)},
                         MAP_EMPTY},
    [MT_WALL_LEFT] = {{SE_FRAME(TILE_WALL_V_JOINT, 0), 0, SE_FRAME(TILE_WALL_V, 0), 0}, MAP_EMPTY},
    [MT_WALL_RIGHT] = {{0, SE_FRAME(TILE_WALL_V_JOINT, MAP_SE_FLIP_H), 0,
                        SE_FRAME(TILE_WALL_V, MAP_SE_FLIP_H)},
                       MAP_EMPTY},
    [MT_SPOTS + 0] = SPOTS(BANK_NAVY),
    [MT_SPOTS + 1] = SPOTS(BANK_TEAL),
    [MT_SPOTS + 2] = SPOTS(BANK_PLUM),
    [MT_SPOTS + 3] = SPOTS(BANK_RUST),
};

// The frame: one screen of 15 x 10 metatiles on background 2. The field
// inside is empty (transparent), showing the pattern behind it.
#define TOP_ROW                                                                                    \
    MT_CORNER_LEFT, MT_TOP, MT_TOP, MT_TOP, MT_TOP, MT_TOP, MT_TOP, MT_TOP, MT_TOP, MT_TOP,        \
        MT_TOP, MT_TOP, MT_TOP, MT_TOP, MT_CORNER_RIGHT
#define SIDE_ROW MT_WALL_LEFT, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, MT_WALL_RIGHT
static const u16 frame_cells[15 * 10] = {
    TOP_ROW,  SIDE_ROW, SIDE_ROW, SIDE_ROW, SIDE_ROW,
    SIDE_ROW, SIDE_ROW, SIDE_ROW, SIDE_ROW, SIDE_ROW,
};

const MapLayer frame_layer = {
    .width = 15,
    .height = 10,
    .cells = frame_cells,
    .metatiles = metatiles,
    .metatile_count = MT_COUNT,
    .bg = 2,
};

// Each level style's pattern: a single metatile repeated over the whole
// background (MAP_LAYER_WRAP).
static const u16 spot_cells[LEVEL_STYLES] = {MT_SPOTS, MT_SPOTS + 1, MT_SPOTS + 2, MT_SPOTS + 3};
#define PATTERN(style)                                                                             \
    {.width = 1,                                                                                   \
     .height = 1,                                                                                  \
     .cells = &spot_cells[style],                                                                  \
     .metatiles = metatiles,                                                                       \
     .metatile_count = MT_COUNT,                                                                   \
     .bg = 3,                                                                                      \
     .flags = MAP_LAYER_WRAP}

const MapLayer pattern_layers[LEVEL_STYLES] = {PATTERN(0), PATTERN(1), PATTERN(2), PATTERN(3)};
